const SENTENCES = [
  {time:0.0, length:5.0, en:"We must respect the will of the individual.", ja:"個人の意志は尊重しなければいけない。"},
  {time:5.0, length:7.0, en:"Take it easy. I can assure you that everything will turn out fine.", ja:"気楽にいけよ。大丈夫、すべてうまくいくさ。"},
  {time:12.0, length:9.0, en:"Let go of your negative outlook on life. Always maintain a positive attitude.", ja:"悲観的な人生観を捨てて、前向きな態度を常に持ち続けよう。"},
  {time:21.0, length:9.0, en:"You should be fair to everyone regardless of national origin, gender, or creed.", ja:"生まれた国、性別、信条に関係なく、誰に対しても公平でなくてはならない。"},
  {time:30.0, length:5.0, en:"Equality is guaranteed by the Constitution.", ja:"平等は憲法で守られている。"},
  {time:35.0, length:7.0, en:"He leaned against the pillar and gazed at the Statue of Liberty.", ja:"彼は柱に寄り掛かって、自由の女神像をじっと見つめた。"},
  {time:42.0, length:11.0, en:"A woman passed by me giving off a subtle scent of perfume. It reminded me of my ex-girlfriend.", ja:"香水のほのかな香りを漂わせながら、一人の女性が僕の前を通り過ぎた。前の彼女のことを思い出してしまった。"},
  {time:53.0, length:6.0, en:"\"Natto\" smells awful but tastes terrific.", ja:"納豆は臭いはひどいけれど味は最高。"},
  {time:59.0, length:8.0, en:"\"I'm soaked with sweat.\" \"Stand back! You stink. Take a shower.\"", ja:"「汗でびしょぬれだよ。」「来ないで！臭いわ。シャワーを浴びて。」"},
  {time:67.0, length:7.0, en:"Bob was so beside himself that he could scarcely tell fact from fiction.", ja:"ボブはひどく取り乱していて、現実と虚構の区別がほとんどできなかった。"},
  {time:74.0, length:9.0, en:"His new novel, which combines prose with his gift for poetry, is going to be published.", ja:"まもなく出版になる彼の小説は、散文に彼の詩の才能を融合させたものだ。"},
  {time:83.0, length:7.0, en:"An up-to-date edition of the encyclopedia will come out next month.", ja:"来月、その百科事典の最新版が出る。"},
  {time:90.0, length:9.0, en:"Ms. Yamada translated the fascinating fairy tale into plain Japanese.", ja:"山田さんがその心ひかれるおとぎ話をやさしい日本語に翻訳した。"},
  {time:99.0, length:7.0, en:"The following passage is quoted from a well-known fable.", ja:"以下の一節は有名な寓話からの引用です。"},
  {time:106.0, length:7.0, en:"\"Are you familiar with contemporary literature?\" \"I know next to nothing about it.\"", ja:"「現代文学に詳しいですか？」「ほとんど知りません。」"},
  {time:113.0, length:6.0, en:"At times I confuse \"curve\" with \"carve.\"", ja:"時々、\"curve\"と\"carve\"を混同してしまう。"},
  {time:119.0, length:7.0, en:"Don't be shy. Your pronunciation is more or less correct.", ja:"恥ずかしがらないで。あなたの発音はだいたい合っています。"},
  {time:126.0, length:9.0, en:"This article contains tips for those who are eager to increase their vocabulary.", ja:"この記事には、語彙を本気で増やしたいと思う人々に役立つ情報が含まれています。"},
  {time:135.0, length:10.0, en:"His latest works are on display at the city hall. They are fabulous beyond description.", ja:"彼の最新の作品が市庁舎で展示されているの。言葉にできないほど素敵よ。"},
  {time:145.0, length:9.0, en:"\"Could you move over a little?\" \"Oh, sorry. I didn't realize I was taking up so much space.\"", ja:"「少し詰めていただけませんか？」「あ、ごめんなさい。こんなに場所を取っていたなんて気付きませんでした。」"},
  {time:154.0, length:7.0, en:"\"What's this ugly object?\" \"This is a piece of abstract art!\"", ja:"「この不格好な物体は何？」「これは抽象芸術の作品だよ！」"},
  {time:161.0, length:10.0, en:"I begged Richie to lend me a hundred bucks, but he shook his head, saying, \"I'm broke, too.\"", ja:"100ドル貸してくれとリッチーに頼んだら、彼は「俺もお金がないんだよ！」と言って首を横に振った。"},
  {time:171.0, length:9.0, en:"\"I'm apt to buy things on impulse whenever something is on sale.\" \"So am I.\"", ja:"「安売りをしているといつも衝動買いしてしまうたちです。」「私も。」"},
  {time:180.0, length:9.0, en:"As it is, ordinary people cannot afford to purchase such luxuries.", ja:"実際のところ、普通の人々にはそんな贅沢品を購入する余裕はない。"},
  {time:189.0, length:8.0, en:"As we anticipated, the unemployment rate has risen three quarters in a row.", ja:"予期していた通り、失業率は3四半期連続で上昇した。"},
  {time:197.0, length:12.0, en:"I have to cut down on my expenses, so from now on, I'm going to keep track of them on a daily basis.", ja:"出費を切り詰めないと。だから、これからは使ったお金は一日単位で記録していくつもりだ。"},
  {time:209.0, length:7.0, en:"In any case, the union has to compromise to a certain extent.", ja:"いずれにせよ、組合側はある程度妥協しなければならない。"},
  {time:216.0, length:8.0, en:"Competent mechanics are in great demand, so they earn decent wages.", ja:"有能な整備士は引っ張りだこだから、なかなかの賃金を稼げる。"},
  {time:224.0, length:7.0, en:"The president announced a concrete plan to carry out welfare reform.", ja:"大統領は福祉改革を実行するための具体的な計画を発表した。"},
  {time:231.0, length:9.0, en:"His policy will no doubt lead to dismal consequences. It needs a thorough review.", ja:"彼の政策はきっと暗い結果を招くだろう。徹底的な見直しが必要だ。"},
  {time:240.0, length:8.0, en:"It goes without saying that the aging of society is inevitable.", ja:"社会の高齢化が避けられないことは言うまでもない。"},
  {time:248.0, length:12.0, en:"Please take a look at this chart. It indicates that juvenile delinquency is on the increase at an alarming rate.", ja:"この表をご覧になって下さい。少年非行が深刻な割合で増加していることを示しています。"},
  {time:260.0, length:9.0, en:"In many business districts, there are a lot of vacant lots which have been for sale for years.", ja:"多くの商業地区では、数年間売りに出されている空き地がたくさんある。"},
  {time:269.0, length:8.0, en:"The population density in the metropolis is gradually decreasing.", ja:"大都市の人口密度が徐々に低下している。"},
  {time:277.0, length:10.0, en:"In all likelihood, the birthrate will continue to decline steadily for years to come.", ja:"ほぼ間違いなくこの先数年、出生率は減少の一途をたどるだろう。"},
  {time:287.0, length:6.0, en:"The power plant supplies the remote county with electricity.", ja:"その発電所は遠く離れた郡に電気を供給している。"},
  {time:293.0, length:6.0, en:"You are not allowed to operate this device without permission.", ja:"許可なくこの装置を操作することはできません。"},
  {time:299.0, length:6.0, en:"In fact, the inhabitants have been exposed to radiation.", ja:"実は、住民たちは放射能にさらされてきた。"},
  {time:305.0, length:8.0, en:"One cannot emphasize too much the potential danger of nuclear energy.", ja:"核エネルギーの潜在的な危険性は、いくら強調してもし過ぎるということはない。"},
  {time:313.0, length:10.0, en:"For years the press overlooked the problem. But now, if anything, they are making too much of it.", ja:"過去数年間その問題を見過ごしていた報道機関が、今ではどちらかと言えばそのことを重視し過ぎている。"},
  {time:323.0, length:7.0, en:"As well as cultivating grain, the farmer runs a grocery store.", ja:"穀物を栽培するだけでなく、その農場経営者は食料雑貨店も経営している。"},
  {time:330.0, length:7.0, en:"The research institute was established in the late 1960s.", ja:"その研究所は1960年代後半に設立された。"},
  {time:337.0, length:9.0, en:"Why don't you consult Starr in person? He's by far the most prominent attorney around here.", ja:"スターさんに直接相談したらどうですか？この辺りでは文句なしでいちばん有名な弁護士ですよ。"},
  {time:346.0, length:7.0, en:"I'll write it down just in case, because I have a bad memory.", ja:"念のためにメモしておきます。記憶力が悪いから。"},
  {time:353.0, length:8.0, en:"The lawyer recommended that his client take legal action against the insurance company.", ja:"弁護士は依頼人に、保険会社に対して法的手段を取ることを勧めた。"},
  {time:361.0, length:6.0, en:"They are entitled to be compensated for their injuries.", ja:"彼らには、けがに対する補償を受ける権利がある。"},
  {time:367.0, length:8.0, en:"So far, no less than 200 people have died of the flu epidemic.", ja:"インフルエンザの流行で、現在までに200人もの人が亡くなっている。"},
  {time:375.0, length:7.0, en:"The effect of those pills is intense but brief.", ja:"それらの錠剤の効果は強烈だが持続性はない。"},
  {time:382.0, length:8.0, en:"He has a habit of biting his nails. It's absolutely disgusting.", ja:"彼は爪を噛む癖がある。あれには本当にぞっとするよ。"},
  {time:390.0, length:8.0, en:"My grandma strained her back when she bent down to hug my son.", ja:"うちの息子を抱こうとしてかがんだときに、おばあちゃんは腰を痛めた。"},
  {time:398.0, length:6.0, en:"If you have a stiff neck, try an herbal remedy.", ja:"肩が凝るなら、薬草治療を試してごらんよ。"},
  {time:404.0, length:8.0, en:"Medical breakthroughs have brought about great benefits for humanity as a whole.", ja:"医学の飛躍的発展は人類全体に多大な恩恵をもたらしてきた。"},
  {time:412.0, length:9.0, en:"We can't apply cloning techniques to cattle, let alone human beings. It's forbidden.", ja:"クローン技術は人間にはもちろん、牛にも応用してはいけない。絶対にしてはならないことだ。"},
  {time:421.0, length:5.0, en:"Whales are classified as mammals.", ja:"鯨は哺乳動物に分類される。"},
  {time:426.0, length:7.0, en:"The theory of evolution is beyond the reach of my imagination.", ja:"進化論は私の想像力の範囲を超えている。"},
  {time:433.0, length:9.0, en:"The biologist is proud of his historic discovery and doesn't mind boasting about it.", ja:"その生物学者は自分の歴史的発見に誇りを持っており、そのことを臆することなく口に出す。"},
  {time:442.0, length:6.0, en:"On ethical grounds, they are opposed to so-called gene therapy.", ja:"倫理的な理由から、彼らはいわゆる遺伝子治療に反対している。"},
  {time:448.0, length:8.0, en:"The initial symptoms of the disease are fever and a sore throat.", ja:"その病気の初期症状は高熱と喉の痛みです。"},
  {time:456.0, length:5.0, en:"The structure of the brain is complex.", ja:"脳の構造は複雑だ。"},
  {time:461.0, length:8.0, en:"Owing to illness, some representatives were absent from the annual conference.", ja:"病気のために年次会議を欠席した代表者もいた。"},
  {time:469.0, length:11.0, en:"Little by little, my son-in-law is recovering from stomach cancer, and now he is in good spirits.", ja:"私の娘婿は徐々に胃癌を克服しつつあり、今は明るく元気だ。"},
  {time:480.0, length:8.0, en:"\"This is fake, isn't it?\" \"Hey, it's a genuine antique.\" \"No way!\"", ja:"「これって偽物だろう？」「何言ってるの。本物の骨董品よ。」「まさか！」"},
  {time:488.0, length:7.0, en:"\"Anything else?\" \"That's it.\" \"For here or to go?\" \"To go.\"", ja:"「ほかにご注文は？」「それだけです。」「こちらでお召し上がりですか？」「持ち帰ります。」"},
  {time:495.0, length:8.0, en:"\"How much is this rug?\" \"$100 including tax.\" \"OK, I'll take it.\"", ja:"「この敷物はおいくらですか？」「税込みで100ドルです。」「じゃあ、これにします。」"},
  {time:503.0, length:9.0, en:"I don't think those pants look good on you. Try these on. They're really in now!", ja:"そのパンツはあなたには似合わないと思う。こっちをはいてみて。今すごく流行っているのよ。"},
  {time:512.0, length:6.0, en:"He got out of the cab in haste, saying, \"Keep the change.\"", ja:"彼は「おつりはいいです」と言って、急いでタクシーを降りた。"},
  {time:518.0, length:8.0, en:"Delivery service is available to our customers for a slight extra charge.", ja:"当店のお客様は、わずかな追加料金で配達サービスをご利用できます。"},
  {time:526.0, length:12.0, en:"\"It's on me.\" \"No. You treat me every time we eat out.\" \"Well, okay. Let's split the check then.\"", ja:"「これは僕のおごり。」「だめよ。外食のときはいつもおごってもらっているし。」「う〜ん、わかった。じゃあ割り勘にしよう。」"},
  {time:538.0, length:6.0, en:"While I was hanging out at the mall, I ran into Ken.", ja:"ショッピングセンターをぶらぶらしていたら、偶然ケンに会った。"},
  {time:544.0, length:10.0, en:"I was short of cash, so I withdrew the $100 that I had deposited in my bank account last week.", ja:"現金が足りなかったので、先週口座に入れた100ドルを引き出した。"},
  {time:554.0, length:5.0, en:"On her way home she was robbed of her purse.", ja:"彼女は帰宅途中にハンドバッグを奪われた。"},
  {time:559.0, length:7.0, en:"\"That's odd! Tell me how it happened.\" \"I'll explain it to you later.\"", ja:"「それは変だわ。どうしてそんなことが起きたのか教えて。」「後で説明するよ。」"},
  {time:566.0, length:8.0, en:"My parents gave me a 6 pm curfew as a punishment because I broke my promise.", ja:"私が約束を破ったので、罰として両親に門限を6時にされた。"},
  {time:574.0, length:7.0, en:"As the proverb goes, \"The end justifies the means.\"", ja:"諺にある通り、「嘘も方便（目的が手段を正当化する）」。"},
  {time:581.0, length:9.0, en:"Now that I've found that there's no one to turn to, I'll have to stand on my own two feet.", ja:"誰も頼れる人がいないとわかったのだから、自分の力でやっていくしかない。"},
  {time:590.0, length:9.0, en:"The chairman cut me off, saying, \"Time to wind things up. Let's take a vote.\"", ja:"議長は私の話を遮って、「話し合いはここまでにして決を採りましょう。」と言った。"},
  {time:599.0, length:10.0, en:"We exchanged frank opinions in the meeting, but consensus is yet to be reached regarding this matter.", ja:"我々は会議で率直な意見を交わしたが、この件に関してはまだ全体の意見がまとまらない。"},
  {time:609.0, length:6.0, en:"\"Do you agree or disagree with him?\" \"I'm on his side.\"", ja:"「あなたは彼と同じ意見？それとも違うの？」「彼のほうを支持するよ。」"},
  {time:615.0, length:6.0, en:"Strictly speaking, his view differs somewhat from mine.", ja:"厳密に言えば、彼の見解は私のものとはいくらか異なる。"},
  {time:621.0, length:8.0, en:"Could you go over it again? I couldn't make out what you were getting at.", ja:"もう一度詳しく説明していただけませんか？お話の意図がわかりませんでした。"},
  {time:629.0, length:10.0, en:"No one backed me up at first, but eventually I talked everyone into going along with my plan.", ja:"僕の案を支持してくれる人は最初は誰もいなかったけれど、最後にはみんなを説得して賛同してもらうことができた。"},
  {time:639.0, length:8.0, en:"\"I admire your perseverance, courage and wisdom.\" \"You flatter me!\"", ja:"「君の不屈の努力、勇気、そして知恵には感心するよ。」「お世辞でもうれしいわ！」"},
  {time:647.0, length:7.0, en:"In making a decision, I rely not on logic but on instinct.", ja:"どうするかを決めるとき、僕は論理ではなく本能を当てにする。"},
  {time:654.0, length:9.0, en:"He came up with an ingenious, sensible solution and immediately put it into practice.", ja:"彼は独創的かつ賢明な解決策を考え出し、直ちにそれを実行に移した。"},
  {time:663.0, length:7.0, en:"From an objective viewpoint, the former is inferior to the latter.", ja:"客観的に見れば、前者は後者よりも劣っている。"},
  {time:670.0, length:10.0, en:"Your idea sounds marvelous in theory, yet I don't think it will work in practice.", ja:"あなたの考えは理論上はすばらしそうだけれども、実際には機能しないと思います。"},
  {time:680.0, length:9.0, en:"We expected him to defeat his opponent, but he failed to live up to our expectations.", ja:"私たちは彼が相手に勝つことを期待したが、彼はその期待に応えられなかった。"},
  {time:689.0, length:9.0, en:"Ironically, despite their best endeavors, their mission resulted in complete failure.", ja:"皮肉なことだが、彼らの最善の努力にもかかわらず、任務は完全な失敗に終わった。"},
  {time:698.0, length:7.0, en:"Her genius makes up for her lack of firsthand experience.", ja:"実地経験の不足は彼女の天賦の才能で補える。"},
  {time:705.0, length:8.0, en:"She possesses a great capacity for overcoming any obstacle.", ja:"彼女にはどんな障害をも克服できるすばらしい能力がある。"},
  {time:713.0, length:9.0, en:"Without your solid support, the deal would have fallen through. I'm grateful to you.", ja:"あなたの強固な支援がなかったら、その取引は成立しなかったでしょう。感謝しています。"},
  {time:722.0, length:6.0, en:"Bringing flammable items into the cabin is prohibited.", ja:"機内への可燃物の持ち込みは禁止されています。"},
  {time:728.0, length:7.0, en:"Our flight to Vienna was delayed on account of a minor accident.", ja:"ちょっとした事故が原因で、私たちのウィーン行きの便に遅れが出た。"},
  {time:735.0, length:8.0, en:"The plane blew up and plunged into the ocean, killing all the people on board.", ja:"飛行機が爆発して海に墜落し、乗っていた全員が死亡した。"},
  {time:743.0, length:7.0, en:"They are working around the clock looking into the cause of the crash.", ja:"彼らは昼夜休むことなく、その墜落事故の原因を調査している。"},
  {time:750.0, length:6.0, en:"Unfortunately, few passengers survived the catastrophe.", ja:"不幸にも、その大惨事で生き残った乗客はほとんどいなかった。"},
  {time:756.0, length:6.0, en:"The aviation expert analyzed the statistics in detail.", ja:"航空評論家が統計を詳細に分析した。"},
  {time:762.0, length:7.0, en:"On behalf of all the staff, I'd like to express our sympathy for the victims.", ja:"全従業員を代表いたしまして、犠牲者の方々に対してお悔やみを申し上げたいと存じます。"},
  {time:769.0, length:5.0, en:"In a sense, he is to blame for the disaster.", ja:"ある意味、その惨事の責任は彼にある。"},
  {time:774.0, length:5.0, en:"The vehicles are inspected for defects every three months.", ja:"車両は欠陥がないか3ヶ月に1度検査される。"},
  {time:779.0, length:7.0, en:"I was amazed to see that our utility bills came to so much!", ja:"うちの光熱費がそんな額になっているのを知ってびっくりした。"},
  {time:0.0, length:6.0, en:"\"Turn the faucet off!\" mom yelled in a rage.", ja:"「水道の栓を閉めなさい！」とお母さんがかんかんになって叫んだ。"},
  {time:7.0, length:5.0, en:"Tighten the lid so the food doesn't go bad.", ja:"食べ物が腐らないように蓋をしっかり閉めなさい。"},
  {time:13.0, length:5.0, en:"\"Can I borrow your scissors?\" \"Sure, here you are.\"", ja:"「ハサミを貸してもらえる？」「もちろん。はいどうぞ。」"},
  {time:18.0, length:8.0, en:"You can substitute some transparent glue for a needle and thread.", ja:"針と糸の代わりに透明な接着剤を使っても結構です。"},
  {time:23.0, length:5.0, en:"I dyed this fabric and it shrank.", ja:"この織物を染めたら縮んでしまった。"},
  {time:31.0, length:8.0, en:"I'm getting rid of this leather jacket because it's worn out at the elbows.", ja:"この革のジャケットは処分するよ。両肘の部分がすり減って穴があいているから。"},
  {time:36.0, length:7.0, en:"Add some flour to the mixture and stir it until it becomes thick.", ja:"その混ぜ合わせたものに小麦粉を加えて、とろみがつくまでかき混ぜましょう。"},
  {time:44.0, length:10.0, en:"\"What should we do with the leftovers?\" \"Keep them in the fridge for now. I'll heat them in the microwave later.\"", ja:"「残り物をどうしよう？」「とりあえず冷蔵庫に入れておいて。後で電子レンジで温め直すよ。」"},
  {time:51.0, length:14.0, en:"I could have laid out all that money on a new PC, but on second thought I decided to put some aside for a rainy day.", ja:"新しいパソコンに全額つぎ込むこともできたが、考え直して、まさかの時のために多少は残しておくことにした。"},
  {time:61.0, length:8.0, en:"A cell phone has become something of a necessity, and I can't do without one.", ja:"携帯電話はちょっとした必需品になったことだし、それなしではやっていけない。"},
  {time:75.0, length:9.0, en:"No sooner had I sat back and relaxed than my wife asked me to do the chores.", ja:"イスにゆったり座ってくつろいだ途端、妻に雑用を頼まれた。"},
  {time:83.0, length:5.0, en:"She laid the baby down and lay down beside him.", ja:"彼女は赤ちゃんを寝かせて自分も隣に横になった。"},
  {time:92.0, length:4.0, en:"Put this stuff away! It's in the way.", ja:"ここにあるものを片付けなさい。邪魔よ。"},
  {time:97.0, length:8.0, en:"When the kids made believe they were dinosaurs, they were scolded by their mother.", ja:"子供たちが恐竜ごっこをしていたら、お母さんに叱られた。"},
  {time:101.0, length:9.0, en:"After he bumped into the shelf, the priceless china fell and shattered into fragments.", ja:"彼が棚にぶつかり、とても高価な陶磁器が落ちて粉々に割れてしまった。"},
  {time:109.0, length:8.0, en:"\"Can you keep an eye on my kids for a while? I need to pick up Ken.\" \"No problem.\"", ja:"「うちの子たちをちょっと見ててもらえる？ケンを迎えに行かないといけないの。」「いいよ。」"},
  {time:118.0, length:7.0, en:"Our neighbor told us off for making a mess in his yard.", ja:"隣の家の人が庭をめちゃくちゃにされたと、私たちにがみがみ説教した。"},
  {time:126.0, length:7.0, en:"Dolly resembles her big sister in every way. You can't tell them apart.", ja:"ドリーはあらゆる面でお姉さんにそっくりだ。二人を見分けることはできないよ。"},
  {time:133.0, length:5.0, en:"As a rule, twins have a lot in common.", ja:"概して、双子には似たところが多い。"},
  {time:140.0, length:6.0, en:"I'm tired of doing the dishes, doing the laundry, and so on!", ja:"皿洗いとか洗濯とか、そういうことにはもううんざり！"},
  {time:145.0, length:7.0, en:"My favorite pastime is strolling along the shore. It's pleasant.", ja:"時間があいたときの一番の楽しみは浜辺の散歩です。気持ちいいですよ。"},
  {time:151.0, length:7.0, en:"\"I'm exhausted! Let's take a break in the shade.\" \"Why not?\"", ja:"「私、もうくたくた。日陰で休憩しましょう。」「そうだね。」"},
  {time:158.0, length:9.0, en:"\"Bob, this vending machine is out of order.\" \"Oh no! I'm dying of thirst!\"", ja:"「ボブ、この自動販売機、故障してるわ。」「何だって！喉が渇いて死にそうだよ！」"},
  {time:165.0, length:7.0, en:"He fainted with hunger and fatigue, but came to after a while.", ja:"彼は空腹と疲労で気を失ったが、しばらくして意識を取り戻した。"},
  {time:174.0, length:7.0, en:"The auditorium was empty except for a single piece of furniture.", ja:"たった一つの家具を除けば、講堂はがらんどうだった。"},
  {time:181.0, length:7.0, en:"Any apartment will do as long as the rent is low. I'm not particular about it.", ja:"家賃が安ければ、どんなマンションでも構いません。こだわりはありませんから。"},
  {time:188.0, length:8.0, en:"His sixty-year-old cousin inherited a piece of real estate by a lake.", ja:"彼の60歳のいとこが湖畔の不動産を相続した。"},
  {time:195.0, length:6.0, en:"So much for small talk. Let's get down to business.", ja:"雑談はこの辺にして、本題に入りましょう。"},
  {time:203.0, length:8.0, en:"Lucy resented the aggressive salesman trying to make her sign the contract.", ja:"ルーシーは、契約書にサインさせようとする強引な販売員に腹を立てた。"},
  {time:209.0, length:8.0, en:"There are a number of factors discouraging us from investing in stocks.", ja:"私たちの株式投資への意欲をそぐような要因がかなりある。"},
  {time:217.0, length:6.0, en:"Japan imports various raw materials and exports manufactured goods.", ja:"日本は様々な原料を輸入し、工業製品を輸出している。"},
  {time:225.0, length:10.0, en:"In the course of its economic development, Japan has abandoned its traditional values.", ja:"経済発展の過程で、日本はその伝統的価値観を捨ててきた。"},
  {time:231.0, length:5.0, en:"The world is faced with an unprecedented crisis.", ja:"世界はかつてない危機に直面している。"},
  {time:241.0, length:8.0, en:"In short, the purpose of the regulations is to protect domestic industries.", ja:"要するに、その規制の目的は国内産業の保護だ。"},
  {time:246.0, length:10.0, en:"In order to keep up its competitiveness in the world, Japan must undertake sweeping deregulation in earnest.", ja:"世界での競争力を維持するためには、日本は大幅な規制緩和に真剣に着手しなければならない。"},
  {time:254.0, length:6.0, en:"We cannot turn our backs on desperate people who are at risk.", ja:"危機にさらされ、わらにもすがる思いでいる人々を、私たちは放っておけない。"},
  {time:264.0, length:8.0, en:"The parliament decided to provide developing countries with financial aid.", ja:"議会は発展途上諸国に財政援助を行うことを決議した。"},
  {time:270.0, length:7.0, en:"Some say the British monarchy should be abolished. What do you think?", ja:"英国の君主制は廃止されるべきだと言う人もいるけど、あなたはどう思う？"},
  {time:278.0, length:7.0, en:"They sought shelter from the attack but found no place to hide.", ja:"彼らは攻撃を逃れる安全な場所を探したが、隠れる場所はどこにもなかった。"},
  {time:285.0, length:8.0, en:"There's little prospect that the two countries will make significant progress in disarmament.", ja:"軍縮において、両国が大きな進展を遂げる見込みはほとんどない。"},
  {time:292.0, length:8.0, en:"The negotiations are under way. Before long, they will enter a crucial phase.", ja:"交渉は進行中だ。そろそろ正念場を迎えるだろう。"},
  {time:300.0, length:5.0, en:"The slaves were anxious to alter their destinies.", ja:"奴隷たちは自分たちの運命を変えたいと切望していた。"},
  {time:308.0, length:6.0, en:"The aristocrats abused their privileges to their hearts' content.", ja:"貴族たちは思うがままに特権を乱用した。"},
  {time:313.0, length:6.0, en:"The revolution in itself, bore no fruit, after all.", ja:"結局、革命それ自体は何の成果ももたらさなかった。"},
  {time:319.0, length:9.0, en:"Bob cut in on our conversation, saying, \"I'm against it!\" But everybody ignored him.", ja:"ボブが「それには反対だ！」と言って会話に割り込んできた。けれども、誰も耳を貸さなかった。"},
  {time:325.0, length:5.0, en:"We skipped his turn on purpose.", ja:"私たちは彼の順番をわざと飛ばした。"},
  {time:334.0, length:6.0, en:"He saw someone being bullied, but he turned a blind eye.", ja:"誰かがいじめられているのを見たのに、彼は見ないふりをした。"},
  {time:339.0, length:11.0, en:"When Nick and I cheated on an exam, I was suspended from school. As for Nick, he got away with it.", ja:"ニックと僕がテストでカンニングしたとき、僕は停学処分。ニックの方はまんまと逃れた。"},
  {time:345.0, length:7.0, en:"They are hostile to Richard because they are jealous of his wealth and status.", ja:"彼らはリチャードの富と地位に対する嫉妬から、彼に敵意を抱いている。"},
  {time:356.0, length:6.0, en:"I hate him! He behaves as if he were somebody.", ja:"彼のことは大嫌い。まるで自分が大物であるかのように振る舞うのよ。"},
  {time:363.0, length:9.0, en:"In spite of our compliments, he frowned and turned away. He was so rude.", ja:"僕たちがほめ言葉をかけたのに、彼は顔をしかめてそっぽを向いた。失礼だ！"},
  {time:369.0, length:7.0, en:"He claimed that the enormous property was at his disposal.", ja:"その莫大な財産は自分が自由にできるものだ、と彼は主張した。"},
  {time:378.0, length:7.0, en:"The more stubborn you are, the more isolated you become.", ja:"頑固になればなるほど孤立するよ。"},
  {time:385.0, length:9.0, en:"\"Don't beat around the bush! What am I supposed to do?\" \"Just wait and see. Time will tell.\"", ja:"「遠回しな言い方はやめてくれ！僕にどうしろって言うんだ？」「慌てずに待つしかありません。時が経てばわかります。」"},
  {time:392.0, length:9.0, en:"Please hand in your assignment via e-mail no later than 5:00 PM on June 10.", ja:"課題は電子メールで6月10日の午後5時までに提出して下さい。"},
  {time:401.0, length:7.0, en:"Joe is anything but diligent. That's why he flunked math again.", ja:"ジョーが勤勉なんてとんでもない。だからまた数学を落としたんだ。"},
  {time:410.0, length:7.0, en:"His thesis doesn't make sense. To begin with, its theme is obscure.", ja:"彼の論文は意味不明。第一、主題が曖昧だ。"},
  {time:417.0, length:5.0, en:"His essay was concise and to the point.", ja:"彼の小論文は簡潔で要領を得ていた。"},
  {time:424.0, length:9.0, en:"\"How are you going to deal with this complicated problem?\" \"Leave it to me! It's a piece of cake.\"", ja:"「この複雑な問題をどう処理するつもり？」「任せとけって。朝飯前さ。」"},
  {time:429.0, length:10.0, en:"\"Nick, I want you to look this over before I turn it in.\" \"Sorry, but I have my hands full right now.\"", ja:"「ニック、これを提出する前にざっと目を通して欲しいの。」「ごめん、今、手が離せないんだ。」"},
  {time:438.0, length:6.0, en:"\"What if I don't meet the deadline?\" \"I bet he'll get mad at you!\"", ja:"「締め切りに間に合わなかったらどうなる？」「きっと彼に怒られるぞ！」"},
  {time:448.0, length:7.0, en:"Your summary leaves nothing to be desired apart from the terrible handwriting.", ja:"字が汚いことを別にすれば、君の要約は完璧だ。"},
  {time:454.0, length:6.0, en:"You ought to think over whether the premise is valid or not.", ja:"その前提が妥当かどうかよく考えるべきだ。"},
  {time:461.0, length:6.0, en:"Above all, scientific terms call for precise definitions.", ja:"とりわけ、科学用語には厳密な定義が要求される。"},
  {time:467.0, length:5.0, en:"First of all, learn the formula by heart.", ja:"何よりもまず、公式を暗記しなさい。"},
  {time:473.0, length:9.0, en:"To calculate the volume, multiply the length by the width by the depth.", ja:"体積を計算する場合は、縦と横と深さを掛けます。"},
  {time:478.0, length:6.0, en:"Tiny cracks were found in the bottom of the barrel.", ja:"樽の底にとても小さなひびがあるのを見つけた。"},
  {time:487.0, length:5.0, en:"This chapter will focus on the concepts of geometry.", ja:"この章では幾何学の概念に焦点をあてます。"},
  {time:493.0, length:8.0, en:"Phil is much more interested in academic subjects than in practical skills.", ja:"フィルは実用的な技能よりも学問的なテーマのほうに興味がある。"},
  {time:498.0, length:10.0, en:"\"Something's gone wrong with this microscope. I need to have it repaired.\" \"Let me see it. Maybe I can fix it.\"", ja:"「この顕微鏡、どこかおかしくなっちゃった。修理してもらわないと。」「見せて。僕が直せるかも。」"},
  {time:506.0, length:10.0, en:"\"What is 'an instrument?\" \"For instance, a gauge, such as a thermometer or a barometer.\"", ja:"「インストゥルメントって何ですか？」「例えば、温度計や気圧計とかの計器がそうです。」"},
  {time:516.0, length:6.0, en:"The minute particles are barely visible to the naked eye.", ja:"その微粒子は肉眼でもかろうじて見える。"},
  {time:526.0, length:7.0, en:"Muscle tissue consists of a vast number of cells.", ja:"筋肉組織はおびただしい数の細胞から成っている。"},
  {time:532.0, length:7.0, en:"This substance is mostly composed of hydrogen and oxygen.", ja:"この物質は主に水素と酸素でできている。"},
  {time:539.0, length:6.0, en:"The exact temperature is 22.68 degrees Celsius.", ja:"正確な気温はセ氏22.68度です。"},
  {time:546.0, length:12.0, en:"\"Naomi likes to show off her perfect figure. I wish I were thin like her. I envy her.\" \"You could go on a diet.\"", ja:"「ナオミは自分の完璧なスタイルをひけらかしたがる。私も彼女みたいに痩せていればなあ。彼女が羨ましいわ。」「ダイエットすれば。」"},
  {time:552.0, length:12.0, en:"I fell in love with Naomi at first sight. Three months later, I took a chance and proposed to her, but she turned me down.", ja:"ナオミに一目惚れした。3ヶ月後、思い切って彼女にプロポーズしてみたが振られてしまった。"},
  {time:564.0, length:8.0, en:"I met the man by chance. He's gentle and smart. What's more, he's single!", ja:"偶然その人に出会ったの。優しくて頭もいいの。おまけに独身！"},
  {time:576.0, length:5.0, en:"His nephew was brought up to be modest and considerate.", ja:"彼の甥は、謙虚で思いやりのある人になるように育てられた。"},
  {time:584.0, length:6.0, en:"I introduced Bob to my folks, and they took to him at once.", ja:"私の両親にボブを紹介したら、二人ともすぐに彼のことが好きになった。"},
  {time:589.0, length:7.0, en:"People should be judged not so much by how they look as by who they are.", ja:"人は外見ではなく、むしろ中身で判断されるべきだ。"},
  {time:595.0, length:7.0, en:"\"It's not your title that counts. That's for sure!\" exclaimed Bob.", ja:"「大切なのは肩書きなんかじゃない。絶対そうだ！」と、ボブは語気を強めて言った。"},
  {time:602.0, length:7.0, en:"As a self-made man put it, \"A man of vision will make good in the end.\"", ja:"自分の力で成功をつかんだ人が言ったように、「先見の明のある人は最後には成功する」。"},
  {time:609.0, length:4.0, en:"Keep in mind that youth is not eternal.", ja:"若さが永遠のものではないことを忘れてはいけない。"},
  {time:616.0, length:9.0, en:"I can't figure out why on earth everybody feels so much contempt for Bob!", ja:"いったいなぜみんながそれ程までにボブを軽蔑するのか、僕にはわからない。"},
  {time:620.0, length:11.0, en:"I can't help laughing at him because he keeps on making stupid mistakes. He'd be the last person to learn his lesson.", ja:"彼のことを笑わずにはいられない。ばかな間違いを繰り返すからね。きっと彼は懲りないんだろうな。"},
  {time:629.0, length:7.0, en:"To make matters worse, he isn't even conscious of annoying us.", ja:"さらに厄介なことに、彼は私たちに迷惑をかけていることさえわかっていない。"},
  {time:640.0, length:7.0, en:"Since I was in a hurry, I put my gloves on inside out by mistake.", ja:"慌てていたから、手袋を間違えて裏返しにはめてしまった。"},
  {time:647.0, length:10.0, en:"Dave is fat and clumsy. When he leaped over the shallow stream, he stumbled and twisted his ankle.", ja:"デイブはデブでドジ。浅い小川を飛び越えた時に、つまずいて足首を捻挫したんだ。"},
  {time:654.0, length:6.0, en:"\"I'm scared of heights.\" \"You're a coward!\"", ja:"「僕、高所恐怖症なんだ。」「弱虫っ！」"},
  {time:664.0, length:7.0, en:"The passive man seldom, if ever, expresses himself in public.", ja:"消極的なその男性が、人前で自己表現をすることはまずない。"},
  {time:670.0, length:6.0, en:"Nick convinced me that all superstitions are irrational.", ja:"迷信はすべて根拠のないものだということが、ニックに言われてよくわかった。"},
  {time:677.0, length:6.0, en:"I tremble with fear at the thought of an injection.", ja:"注射のことを考えると、怖くて震えてしまう。"},
  {time:683.0, length:7.0, en:"Since Bob is lazy at heart, he frequently neglects his duties.", ja:"ボブは根が怠け者だから、与えられた仕事をしばしば怠る。"},
  {time:689.0, length:8.0, en:"While Bob was at work, Jennifer was at home absorbed in silly soap operas.", ja:"ボブが働いている間、ジェニファーは家でくだらないメロドラマに夢中になっていた。"},
  {time:696.0, length:9.0, en:"Bob likes cartoons, but I don't think much of them. As a matter of fact, they're boring.", ja:"ボブはマンガ好きだけど、僕にはそれほどいいものとは思えない。実際、つまらないよ。"},
  {time:704.0, length:8.0, en:"It occurred to me that he was holding something back, because he wouldn't look me in the eye.", ja:"彼が私の目を見ようとしなかったので、何かを隠していると思った。"},
  {time:713.0, length:6.0, en:"When her patience gave out, she grabbed his collar and swore at him.", ja:"彼女は我慢しきれなくなり、襟首をつかんで彼をののしった。"},
  {time:721.0, length:9.0, en:"I must admit we quarrel every now and then, but generally we're on good terms with each other.", ja:"確かに、私たちは時々口げんかもしますが、普段は仲良くやっています。"},
  {time:727.0, length:8.0, en:"\"Do you mind if I stop by your house?\" \"No, not at all. Be my guest!\"", ja:"「君の家に寄ってもいいかい？」「もちろんいいわよ。気兼ねなく！"},
  {time:736.0, length:6.0, en:"Hold on. I'll be right back. Don't hang up!", ja:"ちょっと待ってて。すぐ戻るから。切らないでよ！"},
  {time:0.0, length:7.0, en:"I can't put you up. For one thing, my dad drops in on me from time to time.", ja:"うちには泊められないわ。一つには、時々お父さんがふらっとやって来るから。"},
  {time:8.0, length:7.0, en:"While Jennifer was standing still, Bob was pacing back and forth along the sidewalk.", ja:"ジェニファーがじっと立っている間、ボブは歩道を行ったり来たりしていた。"},
  {time:14.0, length:11.0, en:"\"Let's make up, Lisa.\" \"Stop taking me for granted! We're through for good this time. I mean it!\"", ja:"「仲直りしようよ、リサ。」「私がいて当然だなんて思わないで。私たち、今度は永遠に終わりよ。本気なんだから！」"},
  {time:21.0, length:10.0, en:"Come on! Don't get so emotional, Lisa. I didn't mean to hurt you. Let's talk it over.", ja:"おい！リサ、そう感情的になるなよ。君を傷つけるつもりじゃなかったんだ。じっくり話し合おう。"},
  {time:28.0, length:10.0, en:"\"You betrayed me!\" \"Please forgive me. How can I make it up to you?\" \"I'll get even!\"", ja:"「私を裏切ったわね！」「許してくれよ。どうしたら埋め合わせができるかなあ？」「仕返ししてやるっ！」"},
  {time:39.0, length:5.0, en:"You should confess your sins rather than conceal them.", ja:"自分の罪は隠しておかずに告白したほうがいい。"},
  {time:49.0, length:5.0, en:"Keep your word; otherwise you'll end up losing face.", ja:"約束は守りなさい。そうしないと評判を落としますよ。"},
  {time:59.0, length:8.0, en:"Bob sticks to his moral principles and believes that honesty pays off in the long run.", ja:"ボブは自分の道徳的信条を曲げない男だ。正直でいれば最後には報われると信じている。"},
  {time:64.0, length:10.0, en:"\"Cheer up! You couldn't help it.\" \"I did my best.\" \"I know. Don't dwell on the past. You can start over!\"", ja:"「元気を出して。仕方ないわ。」「やれるだけのことはやったんだ。」「わかってる。過ぎたことにくよくよしないで。やり直せるわよ！」"},
  {time:69.0, length:10.0, en:"\"Jane, please do me a favor and give me a ride to Times Square.\" \"I wish I could, but I'm tied up right now.\"", ja:"「ジェーン、タイムズ・スクェアーまで乗せて行って欲しいんだけど。」「そうしてあげたいのは山々だけど。今、全然時間がないの。」"},
  {time:77.0, length:7.0, en:"As usual, Mike turned up on time. He's very punctual.", ja:"いつものように、マイクは時間通りに現れた。本当に時間に正確な人だ。"},
  {time:87.0, length:7.0, en:"The other day I ran out of gas in the middle of a busy Interstate.", ja:"この前、混雑した幹線道路の真ん中でガス欠してしまった。"},
  {time:97.0, length:10.0, en:"A truck driving ahead of me skidded, turned over, and scattered its load all over the road.", ja:"私の前を走っていたトラックがスリップして横転し、積み荷を路面いっぱいに散乱させた。"},
  {time:104.0, length:7.0, en:"He recalled that a collision had been avoided by sheer luck.", ja:"衝突を避けられたのは運が良かっただけ、と彼は回想した。"},
  {time:111.0, length:7.0, en:"In case of an emergency, get in touch with my agent right away.", ja:"緊急の際には、すぐに私の代理人と連絡を取って下さい。"},
  {time:121.0, length:10.0, en:"\"Jane, where are we heading?\" \"I think we're lost. We went in the wrong direction.\" \"Damn! Pull over!\"", ja:"「ジェーン、俺たちはどこに向かってるんだ？」「迷ったみたい。違う方向に来ちゃったわ。」「何だよ。車を止めてくれ！」"},
  {time:128.0, length:7.0, en:"My rusty Ford broke down, obstructing the intersection.", ja:"僕のさびついたフォードが故障して、交差点をふさいでしまった。"},
  {time:135.0, length:9.0, en:"There are so many fine scratches and dents on its surface, it's no use polishing it.", ja:"表面に細かい傷やへこみがたくさんあるから、磨いても無駄だよ。"},
  {time:145.0, length:11.0, en:"\"Hey, we're stuck in a traffic jam!\" \"Chill out, Joe. Let's take a shortcut! We'll get there in time.\"", ja:"「おい。渋滞にはまっちゃったよ！」「熱くならないで、ジョー。近道しましょう。時間までには着けるわ。」"},
  {time:152.0, length:7.0, en:"\"I've got a flat tire. Can you give me a hand?\" \"I'd be glad to.\"", ja:"「パンクしちゃったよ。手を貸してくれる？」「喜んで。」"},
  {time:161.0, length:8.0, en:"The ambulance went out of control and came close to running over a pedestrian.", ja:"ハンドルがきかなくなった救急車が、危うく歩行者をひきそうになった。"},
  {time:172.0, length:6.0, en:"He contends that primitive life once existed on Mars.", ja:"火星にはかつて原始的な生物が存在していたと彼は力説している。"},
  {time:179.0, length:6.0, en:"The crew is busy preparing for the voyage into outer space.", ja:"乗組員たちは宇宙への航海の準備に忙しい。"},
  {time:187.0, length:7.0, en:"They conducted a series of experiments under zero gravity.", ja:"彼らは無重力状態で一連の実験をおこなった。"},
  {time:193.0, length:7.0, en:"Many astronomers assume that the universe will expand infinitely.", ja:"多くの天文学者は、宇宙は無限に膨張を続けていくものと考えている。"},
  {time:199.0, length:5.0, en:"The astronauts were greeted with spontaneous applause.", ja:"宇宙飛行士たちは自然と沸き起こった拍手で迎えられた。"},
  {time:206.0, length:6.0, en:"A fund was set up with a view to preserving our endangered planet.", ja:"滅亡の危機に瀕した地球を守ろうと、ある基金が設立された。"},
  {time:213.0, length:6.0, en:"The massive flood paralyzed the local transportation network.", ja:"大洪水で現地の交通網が麻痺した。"},
  {time:218.0, length:6.0, en:"The equator divides the globe into two hemispheres.", ja:"赤道は地球を二つの半球に分ける。"},
  {time:224.0, length:5.0, en:"I think it's cruel to trap animals for fur coats.", ja:"毛皮のコートのために動物を罠で捕獲するのは残酷なことだ。"},
  {time:230.0, length:7.0, en:"The organization plays a principal role in wildlife conservation.", ja:"その団体は野生動物の保護において、最も重要な役割を果たしている。"},
  {time:236.0, length:5.0, en:"Many fragile species are on the verge of extinction.", ja:"多くの弱い生物種が絶滅の危機に瀕している。"},
  {time:241.0, length:5.0, en:"The prolonged drought did severe damage to the crops.", ja:"長引く干ばつが収穫に甚大な被害をもたらした。"},
  {time:248.0, length:9.0, en:"Tropical rain forests are quickly disappearing on a global scale. In part, it's due to acid rain.", ja:"熱帯雨林の消滅が地球規模で急速に進んでいます。その原因の一つは酸性雨です。"},
  {time:253.0, length:7.0, en:"It is said that global warming is directly related to carbon dioxide emissions.", ja:"地球温暖化は、二酸化炭素の排出と直接の関係があると言われている。"},
  {time:258.0, length:5.0, en:"The destruction of the ozone layer affects the environment.", ja:"オゾン層の破壊は環境に影響を及ぼす。"},
  {time:267.0, length:7.0, en:"The committee called on all nations to work side by side to curb air pollution.", ja:"委員会は、大気汚染を抑制するために互いに協力し合うよう各国に要請した。"},
  {time:274.0, length:6.0, en:"A satellite was launched into orbit to monitor melting glaciers.", ja:"溶け続ける氷河を監視するために、人工衛星が軌道に打ち上げられた。"},
  {time:279.0, length:10.0, en:"The ecologist has warned us time and again that petroleum is not only a blessing but also a curse.", ja:"石油は天の恵みであると同時に災いのもとでもあるとその生態学者は我々に繰り返し警告してきた。"},
  {time:286.0, length:5.0, en:"The continent is abundant in fossil fuels.", ja:"その大陸は化石燃料が豊富だ。"},
  {time:292.0, length:6.0, en:"The region is relatively rich in mineral resources.", ja:"その地域は鉱物資源が比較的豊かだ。"},
  {time:302.0, length:8.0, en:"Wheat accounts for approximately two-thirds of agricultural production in the area.", ja:"小麦はこの地域の農業生産高のおよそ3分の2を占めている。"},
  {time:307.0, length:6.0, en:"Fertile soil is indispensable for a good harvest.", ja:"良い収穫を得るためには、肥沃な土壌が不可欠だ。"},
  {time:313.0, length:6.0, en:"A humid climate is characteristic of the peninsula.", ja:"湿気の多い気候はその半島の特色です。"},
  {time:321.0, length:6.0, en:"The active volcano erupts at regular intervals.", ja:"その活火山は周期的に噴火する。"},
  {time:327.0, length:6.0, en:"The Panama Canal connects the Atlantic with the Pacific.", ja:"パナマ運河は大西洋と太平洋をつないでいる。"},
  {time:333.0, length:8.0, en:"The geographical features here are similar to those of our prefecture.", ja:"ここの地理的特徴は、私たちの県のそれと似ている。"},
  {time:339.0, length:6.0, en:"More often than not, famine is accompanied by plague.", ja:"たいてい、飢饉になると疫病も発生する。"},
  {time:345.0, length:10.0, en:"A devastating earthquake hit the state capital, leaving tens of thousands of residents homeless.", ja:"壊滅的規模の地震が州都を襲い、数万人の住民が家を失った。"},
  {time:353.0, length:5.0, en:"\"Watch out! The ceiling is giving way!\"", ja:"「気をつけろっ！天井が崩れかけてるぞ！」"},
  {time:359.0, length:8.0, en:"The weather forecast says the typhoon is likely to accelerate and approach the coast.", ja:"台風は速度を上げて沿岸に接近しそうだと天気予報では言っている。"},
  {time:369.0, length:10.0, en:"\"It's still up in the air whether the game will be called off or not.\" \"So what? It makes no difference to me.\"", ja:"「試合が中止になるかどうか、まだ決まらないんだ。」「それがどうしたの？私にとってはどうでもいいことだわ。」"},
  {time:374.0, length:8.0, en:"\"It's foggy, isn't it?\" \"It sure is. But chances are it'll clear up later on.\"", ja:"「霧が濃いね。」「本当ね。でも、たぶんこのあとは晴れるわ。」"},
  {time:382.0, length:6.0, en:"For the most part, modernization is identified with westernization.", ja:"ほとんどの場合、近代化は西欧化と同一のことと見なされる。"},
  {time:392.0, length:8.0, en:"Urban culture appears to be attractive to many people, in particular, to younger people.", ja:"都会の文化は多くの人々の目には魅力的に映る。とりわけ、若者にとっては"},
  {time:400.0, length:5.0, en:"\"Al\" stands for \"artificial intelligence.\"", ja:"AIは人工知能の略です。"},
  {time:406.0, length:7.0, en:"Household appliances are becoming more convenient day by day.", ja:"家庭用の電化製品は日に日に便利になっている。"},
  {time:414.0, length:9.0, en:"My income is not adequate to provide for my family of four, but we have to make the best of it.", ja:"私の収入は四人家族を養うには十分でないけれども、それで何とかやっていくしかない。"},
  {time:419.0, length:6.0, en:"The popularity of a website depends on its content.", ja:"ホームページの人気は内容次第。"},
  {time:426.0, length:7.0, en:"You've got to keep up with it. Once you fall behind, it's hard to catch up.", ja:"遅れずについていかなくちゃ。一度遅れをとったら追い付くのは大変だよ。"},
  {time:435.0, length:6.0, en:"As technology rapidly advances, it's tough to keep pace with it.", ja:"技術は急速に進歩するので、遅れを取らずについていくのは大変だ。"},
  {time:441.0, length:8.0, en:"More and more people are rushing to make use of the interactive nature of the medium.", ja:"ますます多くの人々が、その媒体の双方向的な性質を利用しようと躍起になっている。"},
  {time:448.0, length:7.0, en:"Innovation has something to do with the ability to notice unusual phenomena.", ja:"革新的なものを生み出すこと、それは変わった現象を見逃さない能力と何らかの関係がある。"},
  {time:454.0, length:6.0, en:"A bunch of other companies are imitating our excellent methods.", ja:"多くの他社が我々の優れた方法を真似している。"},
  {time:462.0, length:7.0, en:"The once desolate valley was transformed into a thriving hub of hi-tech business.", ja:"かつての荒涼とした盆地が、繁栄を謳歌するハイテクビジネスの中心地に変ぼうした。"},
  {time:469.0, length:10.0, en:"Although there's still plenty of room for improvement, his invention is superior to conventional equipment in every respect.", ja:"まだ改善の余地はたくさんあるけれども、彼の発明品はあらゆる点で従来の機器よりも優れている。"},
  {time:475.0, length:7.0, en:"The strength of the firm is attributed to its unique and future-oriented strategies.", ja:"その会社の強さは、他社にない未来志向の戦略によって生み出されている。"},
  {time:482.0, length:10.0, en:"SONY has integrated a wide range of functions into this cool gadget. It's catching on from coast to coast.", ja:"ソニーはこのスゴイ機器に多岐にわたる機能を統合させた。全米で評判になり始めている商品だ。"},
  {time:492.0, length:6.0, en:"This tool comes in handy, so I always keep it close at hand.", ja:"この道具は何かと便利だから、いつも手元に置いています。"},
  {time:499.0, length:8.0, en:"\"In general, consumers prefer quantity to quality.\" \"It's the other way around today.\"", ja:"「一般的に、消費者は質よりも量を選びます。」「今は全く逆です。」"},
  {time:509.0, length:6.0, en:"Obviously, the advertisement is aimed at teenagers.", ja:"明らかにその広告は10代の若者層をターゲットにしている。"},
  {time:515.0, length:8.0, en:"The factory now under construction will assemble 1,000 VCR units per day.", ja:"現在建設中のその工場は、一日当たり1000台のビデオデッキを組立てることになる。"},
  {time:523.0, length:5.0, en:"Efficient machinery replaced manual labor.", ja:"効率的な機械が、肉体労働に取って代わった。"},
  {time:529.0, length:8.0, en:"In those days, the gigantic corporation had a virtual monopoly over internal commerce.", ja:"当時、その巨大企業が国内の商業を事実上独占していた。"},
  {time:537.0, length:7.0, en:"With restrictions removed, thousands of new enterprises have come into being.", ja:"制限が解除され、数千の新しい企業が誕生した。"},
  {time:542.0, length:8.0, en:"As a result of his ridiculous venture, he is in danger of going bankrupt.", ja:"ばかげた新事業の結果、彼は破産の危機に瀕している。"},
  {time:550.0, length:11.0, en:"Compared to the previous year, business is looking up in terms of sales. However, we haven't made any profit yet.", ja:"昨年と比べて、売上の数字だけを見れば事業は上向いている。しかしながら、利益はまだ全く出ていない。"},
  {time:557.0, length:10.0, en:"\"I'm going to be transferred to an overseas branch.\" \"Oh, I'll miss you. Please drop me a line.\"", ja:"「海外の支店に転勤することになったよ。」「えっ。寂しくなるわ。手紙でも下さいね。」"},
  {time:565.0, length:8.0, en:"While he was away on business, his wife gave birth to a baby boy.", ja:"彼が出張中に、奥さんが男の子の赤ちゃんを出産した。"},
  {time:576.0, length:8.0, en:"Apparently, Nick wasn't willing to take on the task because it would just add to his burdens.", ja:"どうやらニックは、自分の負担が増えるからその仕事を引き受けたがらなかったようだ。"},
  {time:586.0, length:6.0, en:"Bob had intended to take her out tonight, but he had to work overtime.", ja:"ボブは今夜、彼女とデートするつもりだったが、残業になってしまった。"},
  {time:594.0, length:8.0, en:"\"Please estimate the losses by Friday at the latest.\" \"I'll manage it somehow.\"", ja:"「遅くとも金曜日までには損失の見積りを出して下さい。」「何とかやってみましょう。」"},
  {time:602.0, length:10.0, en:"\"Nick, I'm counting on you.\" \"OK, I'll see to it.\" \"Thanks, I appreciate it.\" \"Don't mention it.\"", ja:"「頼りにしてるわ、ニック。」「大丈夫、きちんとやっておきます。」「ありがとう。感謝するわ。」「いいんですよ。」"},
  {time:608.0, length:6.0, en:"He pretends to be enthusiastic when his boss is around.", ja:"彼は上司がそばにいる時は熱心なふりをする。"},
  {time:616.0, length:8.0, en:"He got promoted at the expense of his colleagues. He should be ashamed of himself.", ja:"彼は同僚を踏み台にして出世した。恥を知るべきだ。"},
  {time:626.0, length:7.0, en:"As the recession set in, temporary employees were laid off one after another.", ja:"景気の後退が始まると、短期契約社員たちは次々に一時解雇を言い渡された。"},
  {time:632.0, length:8.0, en:"Nowadays, many people are out of work against their will. Who is responsible for that?", ja:"最近では、多くの人々が職に就きたくても就けないでいる。誰の責任だろう？"},
  {time:640.0, length:9.0, en:"I've gotten pessimistic, and I'm worried about something I would never have been concerned about before.", ja:"私も悲観的になってきて、以前は決して気にならなかったことに不安を感じている。"},
  {time:647.0, length:7.0, en:"Today, even white-collar workers are confronted with great hardships.", ja:"今日では、サラリーマンでさえ大変な苦難に直面している。"},
  {time:655.0, length:6.0, en:"The authorities are striving in vain to stabilize the currency.", ja:"当局は通貨を安定させようと懸命だが、どうにもならない。"},
  {time:664.0, length:8.0, en:"We've come to the conclusion that nothing is more urgent than reducing Japan's huge deficit.", ja:"日本の膨大な赤字を削減することが何よりも緊急を要することだ、という結論に我々は達した。"},
  {time:671.0, length:5.0, en:"The questionnaires were distributed at random.", ja:"アンケート用紙が無作為に配布された。"},
  {time:677.0, length:9.0, en:"All you have to do is fill in the blanks below. (Please print in black or blue ink.)", ja:"以下の空欄部分にご記入いただくだけで結構です。（黒または青インクではっきりと書いて下さい）"},
  {time:685.0, length:8.0, en:"In addition to a 10% discount, you can pick out an optional excursion for free.", ja:"10%の割引に加えて、無料のオプションツアーを一つ選択できます。"},
  {time:690.0, length:6.0, en:"Round-trip fares to each destination are as follows.", ja:"各目的地までの往復料金は下記の通りです。"},
  {time:699.0, length:6.0, en:"\"Don't forget to confirm your reservation in advance.\" \"I won't.\"", ja:"「事前に予約の確認をするのを忘れないでね。」「ええ。」"},
  {time:707.0, length:7.0, en:"Be sure to check in at least 45 minutes prior to departure time.", ja:"遅くとも出発時刻の45分前には搭乗手続きを必ず完了させて下さい。"},
  {time:713.0, length:7.0, en:"I attached my name tag to my baggage, but it soon came off.", ja:"自分の荷物に名札を付けたけれども、すぐに取れてしまった。"},
  {time:719.0, length:5.0, en:"On average, these packages weigh two pounds.", ja:"これらの小包の重さは平均すると2ポンドです。"},
  {time:726.0, length:6.0, en:"This plastic garbage bag is free of hazardous chemicals.", ja:"このビニール製のゴミ袋は有害な化学物質を含んでいません。"},
  {time:733.0, length:6.0, en:"This flashlight is getting dim. It needs new batteries.", ja:"この懐中電灯は明かりが弱くなってきた。電池を入れ替えないと。"},
  {time:0.0, length:6.0, en:"Excuse me. How often do the shuttle buses run to downtown New York?", ja:"すみません。ニューヨーク市街に行くシャトルバスはどの位の間隔で走ってますか？"},
  {time:5.0, length:6.0, en:"The motel can accommodate as many as 400 guests.", ja:"そのモーテルは400人もの宿泊客を泊められる。"},
  {time:11.0, length:5.0, en:"This suite is three times larger than my condominium.", ja:"このスイートルームは、私の持っているマンションの3倍の広さだ。"},
  {time:17.0, length:7.0, en:"Littering in this facility is subject to a maximum fine of $500.", ja:"この施設内でのゴミの投げ捨てには、最高500ドルの罰金が科せられることがあります。"},
  {time:23.0, length:7.0, en:"That restaurant is always packed. We'd better make a reservation beforehand.", ja:"あのレストランはいつも混んでいるから、事前に予約をした方がいい。"},
  {time:29.0, length:9.0, en:"\"Sorry to interrupt your meal but I'd like a word with you in private.\" \"Can I get back to you later?\"", ja:"「食事の邪魔をして悪いんだけど、ちょっと内密に話がしたいの。」「後で君のところに行くよ。」"},
  {time:34.0, length:5.0, en:"The cook was astonished at his incredible appetite.", ja:"料理人は彼の信じられないほどの食欲にとても驚いた。"},
  {time:41.0, length:7.0, en:"\"What's going on down there? I'm curious.\" \"I have no idea.\"", ja:"「下で何が起こっているの？すごく気になるわ。」「さあ、何だろう。」"},
  {time:48.0, length:8.0, en:"Excited fans were hanging around the rear exit hoping to catch a glimpse of Michael.", ja:"興奮したファンたちが、マイケルを一目見ようと裏口に群がっていた。"},
  {time:57.0, length:5.0, en:"On encountering the celebrity, they asked for his autograph.", ja:"彼らは有名人と出くわすなり、サインをねだった。"},
  {time:62.0, length:6.0, en:"Whenever I go abroad, I suffer from jet lag and diarrhea.", ja:"海外に行くと必ず、時差ボケと下痢に悩まされる。"},
  {time:69.0, length:8.0, en:"\"I feel sort of dizzy and I feel like throwing up.\" \"You look pale!\"", ja:"「何だか目まいと吐き気がするよ。」「顔が真っ青よ。」"},
  {time:77.0, length:6.0, en:"Take some aspirin. It will cure you of your headache in no time.", ja:"鎮痛剤を飲めば、すぐに頭痛は治まります。"},
  {time:82.0, length:7.0, en:"\"I'm afraid I'm coming down with something.\" \"You should take a day off.\"", ja:"「何だか体調が悪いなあ。」「一日休みを取った方がいいわよ。」"},
  {time:88.0, length:8.0, en:"Some of the ingredients in this beverage are harmful, especially if you are pregnant.", ja:"この飲料に含まれている成分には有害なものもある。とりわけ、妊娠中の人にとっては"},
  {time:96.0, length:5.0, en:"Good nutrition is vital for an infant's growth.", ja:"十分な栄養摂取は幼児の発育にとって極めて重要です。"},
  {time:102.0, length:6.0, en:"Moderate exercise stimulates the circulation of the blood.", ja:"適度な運動は血行をよくする。"},
  {time:109.0, length:7.0, en:"My physician advised me to refrain from alcohol for the time being.", ja:"当分の間は酒を控えるようにと、医者に忠告された。"},
  {time:117.0, length:8.0, en:"I do want to get into shape and lose some weight, so I go swimming every morning.", ja:"本当に体調を良くしたいし、減量もしたいから、毎朝泳ぎに行っています。"},
  {time:122.0, length:5.0, en:"He caught a nasty cold because he stayed up late last night.", ja:"昨日の夜更かしがたたって、彼はひどい風邪をひいた。"},
  {time:128.0, length:7.0, en:"The surgeon persuaded him to undergo an organ transplant.", ja:"外科医に説得されて、彼は臓器移植手術を受けることにした。"},
  {time:135.0, length:7.0, en:"Since our father is bedridden, we take turns looking after him.", ja:"父が寝たきりなので私たちが交代で面倒を見ています。"},
  {time:143.0, length:10.0, en:"Our hypothesis is that eating excessive amounts of junk food contributes to early mortality.", ja:"ジャンクフードの過剰な摂取は早死にの一因になる、というのが我々の仮説だ。"},
  {time:148.0, length:8.0, en:"The government did not take appropriate measures to prevent the infection from spreading.", ja:"政府は感染の拡大を未然に防ぐための適切な措置を取らなかった。"},
  {time:155.0, length:5.0, en:"The minister was obliged to resign from the Cabinet.", ja:"その大臣は内閣からの辞任を余儀なくされた。"},
  {time:162.0, length:8.0, en:"Many people regard the current compulsory education system as being obsolete.", ja:"多くの人々は、現行の義務教育制度が時代遅れであると考えている。"},
  {time:172.0, length:6.0, en:"Many people encouraged me to fulfill my ambitions.", ja:"大きな目標を実現するようにと、たくさんの人が私を励ましてくれた。"},
  {time:180.0, length:8.0, en:"To make his dreams come true, he dropped out of school and made his way to Tokyo.", ja:"自分の夢を実現させるために、彼は学校を中退して東京を目指した。"},
  {time:185.0, length:10.0, en:"\"What do you do?\" \"I'm a college student, a freshman at Harvard.\" \"What's your major?\" \"Philosophy.\"", ja:"「普段は何をなさってるんですか？」「大学生です。ハーバードの1年です。」「専攻は？」「哲学です。」"},
  {time:193.0, length:8.0, en:"Tuition will be raised by nearly ten percent as of April 1, 2001.", ja:"2001年4月1日から授業料が10%近く値上げになります。"},
  {time:199.0, length:8.0, en:"\"I'm of two minds whether to apply for the scholarship or not.\" \"Give it a try!\"", ja:"「奨学金を申し込もうかどうか悩んでるの。」「やるだけやってみなよ！」"},
  {time:207.0, length:8.0, en:"As soon as he graduated from Keio University, he took over his family's business.", ja:"彼は慶応大学を卒業するとすぐに家業を継いだ。"},
  {time:217.0, length:6.0, en:"You aren't cut out for the military because of its rigid discipline.", ja:"軍の規律は厳格だから、あなたはそっちの世界には向かないわ。"},
  {time:225.0, length:6.0, en:"I am determined to make a living as a playwright at all costs.", ja:"私はどんな犠牲を払ってでも、脚本家で食べていくと心に決めている。"},
  {time:233.0, length:5.0, en:"As he grew up, he learned to put things in perspective.", ja:"彼も大人になって、物事を総合的な視野で見られるようになった。"},
  {time:241.0, length:7.0, en:"Conformity is an essential element of our homogeneous community.", ja:"同じような人々からなる私たちの地域社会では、体制に従おうとする意識は不可欠な要素である。"},
  {time:247.0, length:10.0, en:"I'd rather go my own way than toil away for a company. Trying to fit into a mold gets me nowhere!", ja:"会社のためにあくせく働くよりは、我が道を行くほうがいい。型にはまろうとしたって何の得にもならないよ！"},
  {time:253.0, length:10.0, en:"Tom takes after his uncle in personality. I mean, he is obstinate by nature. He never gives in.", ja:"トムは性格が彼のおじに似ている。つまりその、生まれつきの頑固者。彼は絶対に折れない。"},
  {time:258.0, length:7.0, en:"When the time is ripe, be bold and go for it! I'll stand by you.", ja:"機が熟したら、大胆に突き進むんだ！僕がいつもそばにいる。"},
  {time:265.0, length:8.0, en:"I'll stand up for what I believe in and won't yield to any threats.", ja:"自分の信念を守るためには立ち上がるし、いかなる脅威にも屈しないつもりだ。"},
  {time:275.0, length:6.0, en:"\"If only I could conquer my weaknesses!\" \"It's up to you.\"", ja:"「自分の弱点を克服できさえすればなあ。」「あなた次第よ。」"},
  {time:285.0, length:8.0, en:"You should make the most of this rare opportunity to demonstrate your talent.", ja:"自分の才能を示すために、めったにないこの機会を最大限に利用するべきだ。"},
  {time:292.0, length:7.0, en:"You won't let me down. I have great faith in you. You can make it!", ja:"僕をがっかりさせないよね。信頼しているよ。君ならうまくやれるさ！"},
  {time:300.0, length:6.0, en:"The spectators were moved by her graceful performance.", ja:"観客たちは彼女の優雅な演技に感動した。"},
  {time:306.0, length:7.0, en:"In 1995, Ando received architecture's most prestigious award.", ja:"1995年、安藤氏は建築における最も権威ある賞を受賞した。"},
  {time:314.0, length:9.0, en:"In the face of adversity, Mike accomplished an extraordinary feat. He deserves praise.", ja:"逆境をものともせず、マイクはすばらしい偉業を成し遂げた。称賛を受けるのは当然だ。"},
  {time:321.0, length:5.0, en:"The audience was impressed by his eloquent lecture.", ja:"聴衆は彼の説得力のある講義に感銘を受けた。"},
  {time:327.0, length:6.0, en:"From a humble background, John achieved worldwide fame.", ja:"庶民の身から、ジョンは世界的な名声を勝ち取った。"},
  {time:334.0, length:7.0, en:"He accumulated a tremendous fortune during the postwar era.", ja:"彼は戦後に莫大な財産を築いた。"},
  {time:343.0, length:8.0, en:"He used to be well off and generous, but now he lives from hand to mouth.", ja:"彼は以前は裕福で気前もよかったけれど、今ではその日暮らしだ。"},
  {time:348.0, length:7.0, en:"Nick is by no means satisfied with the reward. He is selfish and greedy.", ja:"ニックは決してその報酬に満足していない。彼は自己中心的で欲が深い。"},
  {time:354.0, length:13.0, en:"\"You owe me $200 altogether, Bob. When are you going to pay me back?\" \"I'm sorry, I'm hard up.\" \"There you go again!\"", ja:"「全部で200ドル貸してるのよ、ボブ。いつ返すつもりなの？」「ごめん、金欠なんだ。」「またなの？」"},
  {time:361.0, length:6.0, en:"To Brian's surprise, his debt amounted to a considerable sum.", ja:"ブライアンが驚いたことに、借金はかなりの額になっていた。"},
  {time:369.0, length:6.0, en:"Stop clinging to your glory days, or you'll be left behind.", ja:"過去の栄光にしがみつくのはやめないと、取り残されるわよ。"},
  {time:376.0, length:7.0, en:"You cannot escape from today's harsh realities, so you must adapt to them.", ja:"今日の厳しい現実からは逃れられない以上、それに順応しなければならない。"},
  {time:389.0, length:8.0, en:"Prosperity does not last forever. In other words, it will come to an end one of these days.", ja:"繁栄は永遠に続くものではない。つまり、いつかは終わりを迎えるものだ。"},
  {time:395.0, length:7.0, en:"Proper qualifications are required for the position; computer literacy is a must.", ja:"その職種には相応の資格や能力が必要で、コンピューターが使えることは絶対条件である。"},
  {time:401.0, length:7.0, en:"Enclose your resume in this envelope and submit it to the personnel department.", ja:"この封筒に履歴書も入れて人事部に提出してください。"},
  {time:408.0, length:8.0, en:"It's optimistic of you to believe that things will work out. At best there's a fifty-fifty chance.", ja:"物事がうまく行くと信じるなんて君も楽観的だね。可能性はせいぜい50%だよ。"},
  {time:416.0, length:5.0, en:"Registration forms can be obtained free of charge.", ja:"登録用紙は無料で入手できます。"},
  {time:423.0, length:6.0, en:"Please give us a call now if you want to participate in the workshop!", ja:"この講習会に参加をご希望の方は、今すぐお電話下さい。"},
  {time:430.0, length:12.0, en:"For further inquiries, please feel free to contact us toll-free at 1-800-555-1212.", ja:"さらにご質問がありましたら、どうぞご遠慮なくフリーダイヤル1-800-555-1212までお電話下さい。"},
  {time:438.0, length:8.0, en:"\"How's it going, Bob?\" \"Couldn't be better! I did well in my job interview!\" \"Good for you!\"", ja:"「ボブ、最近どう？」「最高だよ！就職面接がうまくいったんだ。」「やったじゃない！」"},
  {time:443.0, length:8.0, en:"He gave instructions to the trainees, but they couldn't make heads or tails of them.", ja:"研修生たちは、彼から与えられた指示がさっぱりわからなかった。"},
  {time:449.0, length:9.0, en:"You can't do two things at one time! It's out of the question. Do them one by one.", ja:"一度に二つのことはできないよ。無理に決まってる。一つずつやりなよ。"},
  {time:461.0, length:9.0, en:"\"Bob, don't disturb her. Mind your own business,\" he whispered.", ja:"「ボブ、彼女の邪魔をしちゃだめだぞ。ちょっかいを出すなよ。」と彼は小声で言った。"},
  {time:469.0, length:7.0, en:"If you persist in bothering her like that, she'll lose her temper.", ja:"そうやってしつこく彼女を困らせると、彼女も怒り出すぞ。"},
  {time:477.0, length:6.0, en:"He was so childish that he couldn't resist temptation.", ja:"彼はあまりに子供だから誘惑に勝てなかった。"},
  {time:486.0, length:7.0, en:"\"Stop making a fuss. It really gets on my nerves!\" she shouted.", ja:"「ぎゃあぎゃあ言うのはやめて。本当にいらいらするわ。」と彼女は叫んだ。"},
  {time:495.0, length:8.0, en:"There's no point in talking back to Nick. He is a dictator, so to speak.", ja:"ニックに口答えしたって無駄だよ。言ってみりゃ彼は独裁者さ。"},
  {time:502.0, length:9.0, en:"They are very polite in his presence, but actually, they always talk about him behind his back.", ja:"彼女たちは彼の前ではとても礼儀正しいが、実際には、いつも陰口を叩いている。"},
  {time:508.0, length:7.0, en:"\"You despise Nick, don't you?\" \"On the contrary! I look up to him.\"", ja:"「ニックを軽蔑しているんだろう？」「とんでもない！尊敬しているわ。」"},
  {time:515.0, length:6.0, en:"His constant insults aroused her anger.", ja:"彼の絶え間ない侮辱が、彼女の怒りをかき立てた。"},
  {time:523.0, length:8.0, en:"I'm fed up with just shuffling papers and pouring coffee. I've made up my mind to quit.", ja:"書類の整理とかお茶くみには、ほとほとうんざり。会社を辞めることに決めたわ！"},
  {time:532.0, length:12.0, en:"In reality, many people have difficulty making ends meet. How can you get by on 100,000 yen a month?", ja:"実際、多くの人々が家計のやりくりに苦労している。月々10万円でどうしたらやっていけるだろう？"},
  {time:539.0, length:9.0, en:"Female clerks may well complain about their routines, which are not challenging at all.", ja:"女性職員が自分たちの日常業務に不満を言うのももっともだ。全くやりがいのない仕事だから。"},
  {time:545.0, length:8.0, en:"Thanks to a fundamental restructuring, our surplus has swelled threefold.", ja:"抜本的に事業の再構築をおこなったおかげで、当社の黒字は3倍に膨らんだ。"},
  {time:553.0, length:7.0, en:"Many people today think of loyalty to a company as an absurd notion.", ja:"現在の多くの人が、会社に対する忠誠はばかげた考えだと思っている。"},
  {time:565.0, length:8.0, en:"I have to commute all the way from a distant suburb. I'm sick of it!", ja:"僕は遠い郊外からわざわざ通勤しなければいけない。もううんざりだ！"},
  {time:574.0, length:6.0, en:"I want to spend the rest of my life pursuing my ideals.", ja:"余生は自分の理想の追求に費やしたい。"},
  {time:582.0, length:6.0, en:"After retirement, Teresa devoted herself to caring for orphans.", ja:"現役を引退した後、テレサは孤児の世話に一身を捧げた。"},
  {time:589.0, length:7.0, en:"For the sake of children in need, we cooperated to collect donations.", ja:"困っている子供たちのために、私たちは募金活動に協力した。"},
  {time:597.0, length:6.0, en:"The charity is named after a man who gave away some two billion yen.", ja:"その慈善団体には、およそ20億円の寄付をした人物の名前が付けられている。"},
  {time:603.0, length:6.0, en:"His autobiography was released today and was sold out by noon.", ja:"彼の自叙伝が今日発売され、午前中に完売した。"},
  {time:609.0, length:7.0, en:"Ted, who is often referred to as a man of integrity, is going to run for mayor.", ja:"高潔な人物だと度々称されるテッドが、市長に立候補する。"},
  {time:616.0, length:5.0, en:"The candidate was disappointed by the outcome of the election.", ja:"その候補者は選挙結果に落胆した。"},
  {time:622.0, length:6.0, en:"The municipal council should concentrate more on specific issues.", ja:"市議会は具体的な問題にもっと焦点を当てるべきだ。"},
  {time:628.0, length:7.0, en:"It is the case that those who live on a pension are forced to lead a hard life.", ja:"年金生活者が厳しい生活を強いられているというのは事実です。"},
  {time:635.0, length:5.0, en:"We should leave out this data. It's far from accurate.", ja:"このデータは除外した方がいい。正確と言うにはほど遠いものだ。"},
  {time:640.0, length:5.0, en:"We tend to associate politicians with hypocrisy.", ja:"私たちは政治家というと偽善を連想しがちだ。"},
  {time:646.0, length:8.0, en:"They are primarily concerned with exploiting us, not with enhancing our living standards.", ja:"彼らの一番の関心事は、私たちの生活水準を高めることではなく、私たちから搾取することだ。"},
  {time:653.0, length:10.0, en:"The man once exerted a dominant influence on the conservative party, but now his power is diminishing.", ja:"その男はかつて保守政党に対して支配的影響力を及ぼしていたが、今では彼の力も弱まっている。"},
  {time:658.0, length:9.0, en:"The spokesperson refused to make any comment, saying, \"It's under investigation.\"", ja:"報道担当者は「調査中です」と言って一切のコメントを拒否した。"},
  {time:663.0, length:6.0, en:"The police say there's someone pulling strings behind the scenes.", ja:"背後で糸を引いている人物がいると警察は言っている。"},
  {time:671.0, length:12.0, en:"The executives entertained the bureaucrats at ryotei, or exclusive Japanese restaurants, hoping for something in return.", ja:"役員たちは何らかの見返りを期待して、官僚たちを料亭、すなわち、高級な日本料理店で接待した。"},
  {time:681.0, length:7.0, en:"His secretary flatly denied leaking any confidential information.", ja:"彼の秘書は機密情報はいっさい漏らしていないと明言した。"},
  {time:690.0, length:8.0, en:"No one dares to contradict his/her employer for fear of being fired.", ja:"クビになるのが怖いから、雇用主にあえて逆らおうとする人は誰一人としていない。"},
  {time:696.0, length:7.0, en:"He sacrificed his promising career to retain his dignity.", ja:"彼は自分の尊厳を守るために、将来有望な経歴を犠牲にした。"},
  {time:708.0, length:8.0, en:"I might as well kill myself as reconcile myself to my fate.", ja:"自分の運命に甘んじるくらいなら自殺した方がましだ。"},
  {time:715.0, length:8.0, en:"He was about to commit suicide by swallowing poison when he thought better of it.", ja:"毒物を飲んで自殺をしようとした直前に彼は思いとどまった。"},
  {time:723.0, length:8.0, en:"The vague rumor proved to be false. Nevertheless, some skepticism lingers on.", ja:"その曖昧な噂は嘘だとわかった。だがそれでも、多少の疑いはまだ残る。"},
  {time:0.0, length:10.0, en:"A senior official is suspected of accepting bribes from a company, but there isn't sufficient evidence to arrest him.", ja:"ある政府高官が企業から賄賂を受け取った容疑をかけられている。しかし、逮捕するには証拠が不十分だ。"},
  {time:7.0, length:7.0, en:"Jason, who was in charge of the project, was dismissed for corruption.", ja:"そのプロジェクトの責任者であったジェイソンが、汚職に手を染めた理由で解任された。"},
  {time:15.0, length:6.0, en:"To my knowledge, he has not been involved in the fraud scheme.", ja:"私の知る限り、彼はその詐欺の企みには関与していません。"},
  {time:23.0, length:6.0, en:"They found out the truth while examining a pile of relevant documents.", ja:"関連書類の山を調べていくうちに、彼らは真実をつかんだ。"},
  {time:31.0, length:8.0, en:"During the trial it came to light that they had been covering up illegal transactions for decades.", ja:"彼らが数十年にわたって違法取引を隠蔽していたことが、公判中に明らかになった。"},
  {time:41.0, length:6.0, en:"The detective took down his testimony on the spot, word for word.", ja:"刑事はその場で、彼の証言を一言一句正確に書き取った。"},
  {time:48.0, length:8.0, en:"For the first time in my life, I felt a pang of conscience, but there was no other way out.", ja:"生まれて初めて良心の呵責を感じましたが、そうする以外にその場をしのぐ方法はありませんでした。"},
  {time:54.0, length:6.0, en:"I'm still haunted by a vivid nightmare I had last night.", ja:"昨日の夜に見た生々しい悪夢がまだ頭から離れない。"},
  {time:60.0, length:7.0, en:"By and large, reporters don't hesitate to intrude on one's privacy.", ja:"概して、記者というものは個人のプライバシーを侵害することにためらいを感じない。"},
  {time:68.0, length:5.0, en:"The author revised his manuscript over and over again.", ja:"著者は何度も何度も原稿を手直しした。"},
  {time:74.0, length:6.0, en:"He is second to none when it comes to finding fault with others.", ja:"他人の過ちを指摘することにかけては、彼の右に出るものはいない。"},
  {time:82.0, length:5.0, en:"On the whole, the elite are not sensitive to criticism.", ja:"概して、エリートたちは批判に対して鈍感だ。"},
  {time:88.0, length:8.0, en:"When a tabloid revealed that he was a drug addict, his reputation was all but ruined.", ja:"ある大衆紙に彼は麻薬常用者だと暴露され、彼の評判はほとんど地に落ちた。"},
  {time:95.0, length:7.0, en:"They considered every aspect of the defense program and pointed out numerous flaws.", ja:"彼らはその防衛計画をあらゆる面から検討し、多数の問題箇所を指摘した。"},
  {time:100.0, length:6.0, en:"We will not tolerate anyone who engages in terrorism.", ja:"我々は、誰であろうとテロ活動に携わる者に寛容でいるつもりはない。"},
  {time:106.0, length:7.0, en:"The notorious rebel was ultimately captured and confined to jail.", ja:"悪名高い反乱兵はついに捕らえられ、拘置所に身柄を拘束された。"},
  {time:111.0, length:5.0, en:"Troops were swiftly called in to put down the riot.", ja:"暴動を鎮圧するために、直ちに軍隊が派遣された。"},
  {time:119.0, length:6.0, en:"We should appeal to reason instead of resorting to violence.", ja:"私たちは暴力に頼るのではなく、理性に訴えるべきだ。"},
  {time:126.0, length:6.0, en:"I suggest we adopt flexible tactics for the moment.", ja:"当分の間は柔軟な戦術を取ってみてはどうでしょう。"},
  {time:132.0, length:6.0, en:"The armed forces succeeded in occupying the entire territory.", ja:"軍は全領土を占領することに成功した。"},
  {time:139.0, length:10.0, en:"Under the circumstances, the enemy has no choice but to surrender. They can't hold out any longer.", ja:"このような状況では、敵は降伏せざるを得ない。彼らがこれ以上持ちこたえることは不可能だ。"},
  {time:144.0, length:6.0, en:"Sooner or later, the hostages will be set free.", ja:"遅かれ早かれ、人質たちは解放されるだろう。"},
  {time:150.0, length:7.0, en:"Under the reign of tyranny, innocent people were deprived of their citizenship.", ja:"専制政治による支配のもとで、罪のない人々が市民権を剥奪された。"},
  {time:156.0, length:5.0, en:"Some soldiers were reluctant to obey the commands.", ja:"その命令にいやいや従う兵士もいた。"},
  {time:162.0, length:5.0, en:"His regime is bound to collapse.", ja:"彼の政権はきっと崩壊する。"},
  {time:172.0, length:8.0, en:"The allies condemned the invasion as a violation of UN resolutions.", ja:"同盟諸国はその侵略行為が国連決議に違反するとして、厳しく非難した。"},
  {time:178.0, length:8.0, en:"We cannot rule out the possibility that civil war will break out in that country.", ja:"その国で内乱が勃発する可能性がないとは断言できない。"},
  {time:185.0, length:6.0, en:"The colony declared independence and became a republic.", ja:"その植民地は独立を宣言し、共和国となった。"},
  {time:190.0, length:6.0, en:"An immense monument was erected in honor of the noble patriot.", ja:"その高潔な愛国者に敬意を表して、巨大な記念碑が建てられた。"},
  {time:195.0, length:6.0, en:"He got down on his knees and prayed for the souls of the deceased.", ja:"彼はひざまずいて故人の霊に祈りを捧げた。"},
  {time:203.0, length:5.0, en:"The Supreme Court is located near the Imperial Palace.", ja:"最高裁判所は皇居の近くにある。"},
  {time:211.0, length:6.0, en:"The pro-choice group protested against a ban on abortion.", ja:"中絶合法賛成派グループが中絶の禁止に対して抗議した。"},
  {time:217.0, length:5.0, en:"Senator Ford remained neutral in the bitter controversy.", ja:"フォード上院議員はその激しい論争において、中立の立場を守った。"},
  {time:223.0, length:8.0, en:"Ford has been in a difficult situation all week long. He is no longer capable of coping with it.", ja:"フォード氏はここ一週間ずっと困難な立場に置かれている。もはや、彼にはどうすることもできない。"},
  {time:229.0, length:6.0, en:"The summit talks are to be broadcast simultaneously throughout the world.", ja:"首脳会談は世界中で同時に放送される予定だ。"},
  {time:234.0, length:5.0, en:"Diplomatic dialogue helped put an end to the conflict.", ja:"外交的対話のおかげでその紛争に終止符を打つことができた。"},
  {time:240.0, length:9.0, en:"Johnson was appointed as a goodwill ambassador to foster mutual understanding between the two nations.", ja:"両国の相互理解を深めるために、ジョンソンさんが親善大使に任命された。"},
  {time:245.0, length:6.0, en:"The specialist predicts international tension will build up.", ja:"その専門家は国際的な緊張が高まっていくと予測している。"},
  {time:253.0, length:6.0, en:"In my opinion, permanent peace is nothing but an illusion.", ja:"私の考えでは、恒久的な平和など幻想に過ぎない。"},
  {time:259.0, length:6.0, en:"Ethnic minorities struggle against prejudice, poverty, and oppression.", ja:"民族的少数派は偏見、貧困、抑圧と戦っている。"},
  {time:264.0, length:6.0, en:"We must make every effort to do away with all discrimination.", ja:"すべての差別をなくすために、私たちはあらゆる努力をしなければならない。"},
  {time:273.0, length:5.0, en:"The immigrants have endured physical and mental pain.", ja:"移民たちは肉体的、精神的苦痛に耐えてきた。"},
  {time:279.0, length:7.0, en:"The amendment was rejected because it didn't take racial diversity into account.", ja:"その改正案は、人種の多様性を考慮していないとの理由で却下された。"},
  {time:285.0, length:5.0, en:"Needless to say, the refugees were longing for freedom.", ja:"言うまでもなく、難民たちは自由を強く求めていた。"},
  {time:291.0, length:8.0, en:"According to a survey, three in five people today are indifferent to foreign affairs.", ja:"ある調査によると、今日では5人中3人が外交問題には無関心だそうだ。"},
  {time:297.0, length:8.0, en:"What will become of Japan-U.S. relations if the security treaty expires?", ja:"安全保障条約が期限切れになったら、日米関係はどうなるだろう？"},
  {time:302.0, length:8.0, en:"Unless Japan eliminates its unfair tariffs, the U.S. will impose sanctions.", ja:"日本が不公平な関税を撤廃しなければ、米国は制裁措置を取るだろう。"},
  {time:309.0, length:6.0, en:"Trade friction might arise between the two nations at any moment.", ja:"両国の間では貿易摩擦がいつ生じてもおかしくない。"},
  {time:314.0, length:9.0, en:"Our top priority is to settle this dispute once and for all, so we are ready to meet them halfway.", ja:"我々の最優先事項はこの論争にきっぱりと決着を付けることだ。そのためには相手側との妥協も覚悟している。"},
  {time:322.0, length:5.0, en:"The federal budget was narrowly approved by Congress.", ja:"連邦予算はかろうじて議会の承認を得た。"},
  {time:330.0, length:7.0, en:"He argues that the administration must look for alternative sources of revenue.", ja:"政府は別の歳入源を探さなければいけない、と彼は主張している。"},
  {time:338.0, length:7.0, en:"A poll shows that an overwhelming majority is in favor of the legislation.", ja:"世論調査の結果から、圧倒的多数の人がその法律を支持していることがわかる。"},
  {time:344.0, length:5.0, en:"The cops are searching for clues to the brutal murder.", ja:"警察はその残虐な殺人事件の手がかりを捜している。"},
  {time:353.0, length:7.0, en:"The man must be insane. He can't distinguish vice from virtue.", ja:"その男は頭がおかしいに違いない。善悪の区別がつけられないんだ。"},
  {time:358.0, length:7.0, en:"The fingerprints left on the weapon correspond with the suspect's.", ja:"凶器に残された指紋は容疑者のものと一致する。"},
  {time:365.0, length:8.0, en:"It took us all by surprise when the noted psychologist was accused of kidnapping.", ja:"その著名な心理学者が誘拐罪で訴えられたことに、私たちはみな驚いた。"},
  {time:372.0, length:6.0, en:"The jury's guilty verdict gave rise to widespread debate.", ja:"陪審団による有罪評決が大論争の引き金となった。"},
  {time:377.0, length:8.0, en:"The man pleaded for mercy, but he was sentenced to twenty years in prison for his crime.", ja:"男は情状酌量を求めたが、犯した罪に対して20年の懲役刑が言い渡された。"},
  {time:384.0, length:7.0, en:"The officer on duty perceived an elderly man coming up behind him.", ja:"勤務中の警官は、一人のお年寄りが自分の背後に近づいてくるのに気付いた。"},
  {time:391.0, length:6.0, en:"He caught sight of a thief attempting to break into the house.", ja:"彼はその家に押し入ろうとしている泥棒を目にした。"},
  {time:399.0, length:6.0, en:"The day before yesterday he witnessed a weird incident in the wilderness.", ja:"おととい、彼はその原野で奇妙な出来事を目撃した。"},
  {time:405.0, length:10.0, en:"I became aware of someone staring at me from across the aisle, so I turned around. But there was no one in sight.", ja:"通路の向こうから、誰かが私をじっと見ているのに気付いたので振り向いた。しかし、誰の姿も見えなかった。"},
  {time:413.0, length:6.0, en:"She screamed with horror as someone took hold of her arm.", ja:"何者かに腕をつかまれ、彼女は怖くて悲鳴を上げた。"},
  {time:420.0, length:6.0, en:"Informed of her safety, he breathed a sigh of relief.", ja:"彼女の無事を知らされて、彼は安堵のため息をついた。"},
  {time:426.0, length:7.0, en:"The bullet penetrated his chest, leaving him in critical condition.", ja:"銃弾が胸を貫通し、彼は危篤状態に陥った。"},
  {time:432.0, length:7.0, en:"At present, it's still uncertain whether it was done deliberately or by accident.", ja:"そうなったのが故意なのか過失なのか、現在のところまだはっきりしない。"},
  {time:442.0, length:7.0, en:"A deli caught fire and burned down, leaving a heap of ashes.", ja:"デリカテッセンから火災が発生し、灰の山を残して全焼した。"},
  {time:448.0, length:9.0, en:"All of a sudden the fireworks warehouse exploded, and it took two days to put out the blaze.", ja:"花火の貯蔵庫が突然爆発し、激しい炎を鎮めるまでに2日間を要した。"},
  {time:454.0, length:8.0, en:"A bomb went off in a thirty-story building, and more than fifty people were seriously wounded.", ja:"30階建てのビルで爆弾が爆発し、50人以上が重傷を負った。"},
  {time:461.0, length:7.0, en:"A cargo vessel, bound for Athens, sank in the Mediterranean without a trace.", ja:"アテネへ向かう一隻の貨物船が、何の痕跡も残さずに地中海で沈没した。"},
  {time:468.0, length:7.0, en:"The reckless men froze to death during their expedition to the Antarctic.", ja:"無謀な男たちが南極探検中に凍死した。"},
  {time:475.0, length:6.0, en:"The tragedy must be remembered so as not to be repeated.", ja:"同じことが繰り返されないように、その悲劇を忘れてはならない。"},
  {time:484.0, length:6.0, en:"The exhibition offers profound insights into ancient civilization.", ja:"その展覧会に行くと古代文明に対する深い理解が得られる。"},
  {time:492.0, length:7.0, en:"Giotto is credited with sowing the seeds of the Italian Renaissance.", ja:"イタリアルネッサンスを開花させるきっかけを作ったのはジョットの功績だ。"},
  {time:499.0, length:7.0, en:"Bob mounted the portrait in a fancy frame, but it was upside down.", ja:"ボブは装飾された額にその肖像画を収めたけれど、上下逆さまだった。"},
  {time:506.0, length:6.0, en:"This magnificent cathedral dates back to the Middle Ages.", ja:"この荘厳な大聖堂の建立は中世にまでさかのぼる。"},
  {time:512.0, length:7.0, en:"Asian religions inspired him to create splendid sculptures.", ja:"アジアの宗教から閃きを得て、彼は複数のすばらしい彫刻作品を生み出した。"},
  {time:518.0, length:6.0, en:"They explored the desert in search of buried treasure.", ja:"彼らは埋蔵された宝物を求めて砂漠を探検した。"},
  {time:525.0, length:8.0, en:"The millionaire insisted on acquiring the masterpiece no matter how much it cost.", ja:"たとえいくらかかろうともその傑作を手に入れると、その大富豪は言い張った。"},
  {time:532.0, length:6.0, en:"Myths and legends should be handed down from generation to generation.", ja:"神話や伝説は代々語り継がれていくべきだ。"},
  {time:538.0, length:6.0, en:"The linguist is fluent in several Chinese dialects.", ja:"その言語学者はいくつかの中国語の方言を流暢に話す。"},
  {time:545.0, length:8.0, en:"The tribe worships its ancestors and speaks its own language, which is not familiar to us.", ja:"その部族は祖先を崇拝し、私たちにはなじみのない独自の言語を話す。"},
  {time:551.0, length:7.0, en:"The anthropologist says old customs still prevail in the province.", ja:"その州ではいまだに古い慣習が根強い、とその文化人類学者は言っている。"},
  {time:559.0, length:8.0, en:"The wicked witch cast an evil spell on the man and turned him into a bug.", ja:"意地の悪い魔女が男にとんでもない魔法をかけて、虫に変えてしまった。"},
  {time:565.0, length:7.0, en:"They proceeded along the steep path, which was the sole access to the border.", ja:"その険しい小道に沿って彼らは前進した。それは国境へたどり着く唯一の方法だった。"},
  {time:571.0, length:7.0, en:"When a big ape emerged from the cave, they got frightened and ran away.", ja:"洞窟から大きな猿が現れると、彼らはびっくりして逃げて行った。"},
  {time:579.0, length:9.0, en:"\"Believe it or not, I saw an alien and then it vanished!\" \"Give me a break!\"", ja:"「信じてくれないかもしれないけど、宇宙人を見たので、消えちゃったのよ！」「冗談はよせよ。」"},
  {time:586.0, length:6.0, en:"Quite a few people have been invited to celebrate the couple's anniversary.", ja:"かなりの数の人々が、その夫婦の結婚記念のお祝いに招待されている。"},
  {time:594.0, length:8.0, en:"It won't be long before everything is ready. In the meantime, help yourself to some snacks.", ja:"もうすぐ準備完了です。その間、軽食をご自由につまんでいてください。"},
  {time:601.0, length:7.0, en:"Dressed in a loud and peculiar outfit, she stood out in the crowd.", ja:"けばけばしい奇妙な服を着ていた彼女は、人込みの中でもひときわ目立った。"},
  {time:608.0, length:5.0, en:"All the guests were touched by her hospitality.", ja:"招かれた人は皆、彼女のもてなしに心を打たれた。"},
  {time:617.0, length:6.0, en:"Her shabby clothes were not suitable for the occasion.", ja:"彼女のよれよれの服は、その場にはふさわしくなかった。"},
  {time:623.0, length:6.0, en:"That topic is too intimate to share with casual acquaintances.", ja:"たまたま知り合った人たちと話すには、その話題は立ち入りすぎている。"},
  {time:631.0, length:8.0, en:"When Tom gets drunk, he gets crude and offensive. Stay away from him.", ja:"トムは酔っぱらうと下品になって、人に不快な思いをさせるから、近づいちゃだめだよ。"},
  {time:638.0, length:5.0, en:"He could hardly comprehend what she was implying.", ja:"彼女がほのめかしていることを彼はほとんど理解できなかった。"},
  {time:643.0, length:6.0, en:"Bob felt embarrassed when he was teased in front of some girls.", ja:"女の子の前でからかわれて、ボブは恥ずかしかった。"},
  {time:649.0, length:6.0, en:"His ambiguous reply made her all the more irritated.", ja:"彼の曖昧な返事はなおさら彼女をいらいらさせた。"},
  {time:655.0, length:6.0, en:"Bob is very timid and blushes when chatting with girls.", ja:"ボブはとても臆病で女の子とおしゃべりすると赤面してしまう。"},
  {time:663.0, length:6.0, en:"Nick looks down on anyone who comes from a rural area.", ja:"ニックは地方出身者なら誰であろうと見下している。"},
  {time:668.0, length:9.0, en:"What's the matter, Bob? You look so miserable. Leave me alone. It's none of your business.", ja:"「どうしたの、ボブ？そんなに暗い顔をして。」「ほっといてくれよ。君には関係ないことだ。」"},
  {time:674.0, length:6.0, en:"Although Bob was in disguise, I recognized him at a glance.", ja:"ボブは変装していたけれども、一目で彼だとわかった。"},
  {time:0.0, length:8.0, en:"\"What are you chuckling about?\" \"Bob, you have your sweatshirt on backwards!\" \"Oops!\"", ja:"「何をくすくす笑ってるんだ？」「ボブ、トレーナーが後ろ前よ。」「あっ！」"},
  {time:6.0, length:6.0, en:"He is not good at making friends and always keeps to himself.", ja:"彼は友達作りが苦手で、いつも一人ぼっちでいる。"},
  {time:12.0, length:8.0, en:"Having found no place he felt he belonged, he was extremely uneasy and lonely.", ja:"自分が受け入れられる場所を見つけられず、彼は極度の不安と孤独に陥っていた。"},
  {time:18.0, length:6.0, en:"I found it pretty hard to adjust to my new surroundings.", ja:"新しい環境に順応するのはかなり大変なことだとわかった。"},
  {time:27.0, length:6.0, en:"I felt utterly out of place among those sophisticated people.", ja:"ああいう洗練された人たちの中で、自分はまったく場違いな気がした。"},
  {time:33.0, length:9.0, en:"To tell the truth, I don't like classical music. On the other hand, Molly is really into it.", ja:"正直言って私はクラシック音楽は好きじゃない。かたや、モリーのほうは完全にはまっている。"},
  {time:41.0, length:4.0, en:"Bob derives pleasure from observing insects.", ja:"ボブは昆虫の観察に楽しみを感じている。"},
  {time:47.0, length:7.0, en:"How about playing cards or something for a change? Sorry, I'm not up for it.", ja:"「気分転換にトランプか何かしない？」「悪いけど、そういう気分じゃないよ。」"},
  {time:55.0, length:6.0, en:"\"After you.\" \"No please, you go ahead.\" \"Thanks.\" \"You're welcome.\"", ja:"「お先にどうぞ。」「いや、あなたの方こそお先にどうぞ。」「すみません。」「どういたしまして。」"},
  {time:61.0, length:8.0, en:"His niece is sociable and mature for her age. She could pass for twenty-something.", ja:"彼の姪は年の割には社交的で大人だ。二十代と言っても通用する。"},
  {time:67.0, length:7.0, en:"Take care of yourself and say hi to your family for me. I will. See you later.", ja:"「じゃあね。家族のみんなによろしく。」「ああ。またね。」"},
  {time:76.0, length:6.0, en:"I'm looking forward to hearing from you. Sincerely, ((IN A LETTER))", ja:"お返事頂けるのを楽しみにしております。敬具"},
  {time:80.0, length:7.0, en:"Can you spare a minute? I'd like to discuss something of importance to both of us.", ja:"ちょっと時間を割いてくれませんか？二人にとって大事なことを話し合いたいんです。"},
  {time:87.0, length:7.0, en:"It may seem trivial to you but for me it's worth paying attention to.", ja:"あなたには些細なことに思えるかもしれませんが、私にとってそれは注意すべきことなんです。"},
  {time:93.0, length:9.0, en:"As far as Bob is concerned, anything goes. By contrast, Jane is very cautious.", ja:"ボブについて言えば、彼はどんなことでも受け入れるタイプだが、対照的にジェーンはとても慎重派だ。"},
  {time:101.0, length:8.0, en:"After an awkward pause, Bill took her by the hand and dragged her upstairs.", ja:"気まずい沈黙の後、ビルは彼女の手を取って上の階に引っ張って行った。"},
  {time:108.0, length:7.0, en:"Bill just wanted to comfort Monica, but she interpreted it as romantic interest.", ja:"ビルはただモニカを慰めたかっただけなのに、彼女は彼が自分に気があるのだと解釈した。"},
  {time:114.0, length:8.0, en:"After making sure she was sound asleep, he crept out of the room and set off.", ja:"彼女が熟睡しているのを確かめて、彼はこっそり部屋を抜け出して旅立った。"},
  {time:121.0, length:9.0, en:"Between you and me, Lisa, I came across Nick passionately embracing a woman.", ja:"ここだけの話だけど、リサ、女の人を熱く抱擁してるニックを見ちゃったんだ。"},
  {time:128.0, length:5.0, en:"Such a remark is open to misunderstanding.", ja:"そういう発言は誤解を招きやすい。"},
  {time:137.0, length:7.0, en:"\"I can't stand it anymore!\" \"Calm down. I'll come over as soon as possible.\"", ja:"「もう我慢できないっ！」「落ちつけよ。すぐそこに行くから。」"},
  {time:145.0, length:6.0, en:"Don't take it literally. He is inclined to exaggerate.", ja:"そんなこと真に受けちゃだめだよ。彼は大げさに言う傾向があるから。"},
  {time:152.0, length:12.0, en:"\"You should apologize to Lisa for making fun of her. You went too far this time.\" \"Yeah... I will, sometime when she's in a better mood.\"", ja:"「リサをばかにしたことを謝るべきだわ。今回はやりすぎよ。」「ああ、そうするよ。そのうち彼女の機嫌が直ったらね。」"},
  {time:160.0, length:10.0, en:"\"Lisa, are you getting along with Nick?\" \"Once in a while, I think of divorcing him.\" \"You must be kidding!\"", ja:"「リサ、ニックとうまくやってる？」「時々、離婚を考えることがあるわ。」「冗談だろ！」"},
  {time:169.0, length:6.0, en:"In tears, she tore up his letter and threw it away.", ja:"彼女は泣きながら、彼からの手紙をめちゃくちゃに引き裂いて捨てた。"},
  {time:174.0, length:8.0, en:"\"Jennifer deceived me!\" \"You should have known better than to trust her.\"", ja:"「ジェニファーにだまされた！」「彼女を信じないくらいの分別があってもよかったのに。」"},
  {time:181.0, length:5.0, en:"Tom regretted having wasted a great deal of his life.", ja:"トムは自分の人生の多くを無駄にしてきたことを後悔した。"},
  {time:187.0, length:6.0, en:"I cannot look back on my adolescence without feeling depressed.", ja:"自分の思春期を振り返ると、いつも憂鬱な気分になる。"},
  {time:199.0, length:10.0, en:"\"Jennifer left me for another guy.\" \"Oh, you must be upset.\" \"Not really. I'm used to it.\"", ja:"「ジェニファーが俺をふって他の男のところにいったよ。」「えっ、それは辛いわね。」「そうでもないよ。慣れてるよ。」"},
  {time:209.0, length:9.0, en:"\"No wonder she didn't show up to see him off.\" \"How come?\" \"They broke up.\" \"Oh, what a pity!\"", ja:"「彼女が見送りに来なかったのも当然だよ。」「どうして？」「二人は別れたんだ。」「えっ、かわいそうに！」"},
  {time:215.0, length:6.0, en:"\"Living here all by myself is torture!\" he sobbed.", ja:"「ここで自分一人だけで生きていくなんて拷問だ」と彼はすすり泣きして言った。"},
  {time:223.0, length:14.0, en:"\"To be honest, I'm crazy about Ken because he's brave, self-confident, and never afraid of taking risks.\" \"If I were you, I'd ask him out!\"", ja:"「正直言うと私。ケンに夢中なの。だって、勇敢で自分に自信を持っていて、それに危険を冒すことを決して恐れないでしょ。」「私ならデートに誘うわ。」"},
  {time:228.0, length:11.0, en:"\"I've been going with Jennifer on and off for ages.\" \"You're as indecisive as ever. Isn't it about time you settled down?\"", ja:"「ずいぶん長い間、ジェニファーとは付き合ったり別れたりの繰り返しだよ。」「相変わらず優柔不断ね。そろそろ落ち着いたらどう？」"},
  {time:234.0, length:10.0, en:"\"It dawned on me that I had been taken in by Jennifer all along.\" \"How naive! Didn't you see through her?\"", ja:"「ジェニファーにずっとだまされていたのがわかってきたよ。」「何てうぶなの。彼女の本性が見抜けなかったの？」"},
  {time:244.0, length:6.0, en:"Even though she is seeing someone else, I won't give her up.", ja:"実際、彼女は誰かと付き合っているけれども、僕は彼女をあきらめない。"},
  {time:253.0, length:11.0, en:"\"Hi, Jane. What's up?\" \"Not much. How about you?\" \"I got married to Jennifer.\" \"Wow! Congratulations!\"", ja:"「やあ、ジェーン。最近どう？」「別に。あなたは？」「ジェニファーと結婚したんだ。」「ええっ、おめでとう！」"},
  {time:259.0, length:6.0, en:"Whenever you're in trouble or feeling down, I'll be there for you.", ja:"大変なことがあったり、落ち込んだりしたときはいつでも、私があなたのそばにいるわ。"},
  {time:273.0, length:4.0, en:"\"Delight\" is the opposite of \"sorrow.\"", ja:"「喜び」は「悲しみ」の反対です。"},
  {time:284.0, length:11.0, en:"\"Jennifer went so far as to call me an idiot and she wouldn't take it back.\" \"Serves you right! You provoked her, didn't you?\"", ja:"「ジェニファーは僕をばか呼ばわりまでして、しかもそれを撤回しないんだ。」「自業自得よ！あなたからけしかけたんでしょう？」"},
  {time:294.0, length:9.0, en:"\"Why do you put up with her arrogance? She's just taking advantage of you.\" \"Shut up!\"", ja:"「彼女の傲慢さにどうして我慢しているの？利用されているだけよ。」「うるさい！」"},
  {time:300.0, length:7.0, en:"Take your time. I know you need a couple of days to reflect on it.", ja:"慌てなくていいですよ。そのことをじっくり考えるには2、3日必要でしょうから。"},
  {time:311.0, length:5.0, en:"Bob has to get through this ordeal on his own.", ja:"ボブは自分の力でこの厳しい試練を乗り切らなければいけない。"},
  {time:317.0, length:6.0, en:"Flies and mosquitoes interfered with his meditation.", ja:"ハエと蚊が彼の瞑想の邪魔をした。"},
  {time:321.0, length:6.0, en:"The sacred ritual took place after being postponed twice.", ja:"2度の延期の後、その神聖な儀式は執り行われた。"},
  {time:332.0, length:8.0, en:"All at once, the Buddhist priest burst into laughter, spoiling the solemn atmosphere.", ja:"お坊さんが突然大声で笑い出し、厳粛な雰囲気を台無しにした。"},
  {time:341.0, length:6.0, en:"Cover your mouth when you cough, sneeze, or yawn.", ja:"咳、くしゃみ、あくびをするときは口を手で隠しなさい。"},
  {time:348.0, length:9.0, en:"\"One of her relatives passed away three days ago.\" \"Oh, that's too bad. I'm so sorry.\"", ja:"「彼女の親戚が3日前に亡くなったんだ。」「えっ、それは大変ね。お気の毒だわ。」"},
  {time:353.0, length:7.0, en:"Besides attending the funeral, she needs to make all the arrangements.", ja:"彼女は葬儀に参列するだけでなく、すべての段取りをつけなければならない。"},
  {time:359.0, length:8.0, en:"\"I feel for you, Jane. Grief doesn't fade away quickly.\" \"I'm OK. I'll get over it.\"", ja:"「ジェーン、気持ちはわかるよ。悲しみはすぐに消えるものじゃない。」「大丈夫。乗り越えてみせるわ。」"},
  {time:365.0, length:5.0, en:"She cherishes the precious memories of her childhood.", ja:"彼女は子供の頃のかけがえのない思い出を大切にしている。"},
  {time:373.0, length:12.0, en:"\"Speaking of Jennifer, she got engaged to a businessman.\" \"I'm at a loss for words! I hope she won't break it off.\"", ja:"「ジェニファーと言えば、彼女、実業家と婚約したんだよ。」「あきれてものが言えないわ。破談にならなきゃいいけどね。」"},
  {time:379.0, length:9.0, en:"These days, the motives for marriage are not necessarily pure. Take Jennifer for example.", ja:"近ごろでは、結婚の動機は必ずしも純粋とは限らない。例えば、ジェニファーを見てごらんよ。"},
  {time:388.0, length:8.0, en:"Go easy on Bob. You know, he's been going through a rough period recently.", ja:"ボブには優しく接してあげてくれよ。ほら、彼は最近ずっと辛いこと続きなんだ。"},
  {time:395.0, length:7.0, en:"\"By the way, do you have the time?\" \"Let's see ... it's a quarter to eight.\"", ja:"「ところで、今何時？」「え〜っと、8時15分前だよ。」"},
  {time:403.0, length:7.0, en:"\"Let's call it a day, Bob. I'm starved.\" \"Yep. I'll buy you dinner.\"", ja:"「ボブ、今日はこの辺までにしましょう。お腹がぺこぺこ。」「ああ。晩飯は僕がおごるよ。」"},
]